### ISSUE TITLE
Missing code-signing certificate

### ISSUE THREAD

**Issue by bilby91** [fastlane/deliver#118]
Hello,

I'm having some issue trying to make deliver work. I build my IPA with the help of `ipa` helpers in fastlane.

If I build an IPA with the command and deploy through Application Loader it works fine. When using deliver, there is a problem with the code signing.

```
ERROR [2015-02-27 14:08:27.25]: [Transporter Error Output]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle XXX [Payload/XXX.app] is invalid. [Missing code-signing certificate.] For more information, visit the iOS Developer Portal."
```

I don't know what is actually happening because the same IPA can be correctly uploaded through Application loader.

**Comment by KrauseFx** [comment]
`fastlane` uses [shenzhen](https://github.com/nomad/shenzhen/) to build the app. You should check out the following issues: https://github.com/nomad/shenzhen/issues/165 and https://github.com/nomad/shenzhen/issues/85

The best way to fix it is to set the provisioning profile in the Xcode project. You can also do that using this action: https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/update_project_code_signing.rb

**Comment by bilby91** [comment]
But the same IPA can be delivered correctly through application loaded but not in deliver. If the signing is wrong it should fail in both cases right ?

**Comment by KrauseFx** [comment]
That's true, because the Application Loader will resign your app before submitting. You could also try `sigh resign` to resign your ipa file.

**Comment by bilby91** [comment]
@KrauseFx Couldn't make it work :( . sigh output seems fine but deliver always fails. Also added the configuration in the xcodeproj and didn't have luck.

**Comment by silvansky** [comment]
Faced the same problem. Action `update_project_code_signing` fails with error, `sigh resign` doesn't help either.

**Comment by pettom** [comment]
I have the same problem.

**Comment by pettom** [comment]
@bilby91 was are able to solve the problem? or do you found another solution? 
I'm sorry for mention.

**Comment by bilby91** [comment]
@pettom Didn't have time to investigate further.

**Comment by pettom** [comment]
Ok, I solve with resign

**Comment by kjf** [comment]
Ran into this one too. Anyone found a solution?

**Comment by saiday** [comment]
Updating to 0.4.2, had the same issue.

**Comment by jaikumarbhambhwani** [comment]
I am running into the same issue. Any solutions to this. Just to point out i have a watchkit extension for which it is giving me "Invalid Provisioning Profile"

**Comment by theoriginalgri** [comment]
I also had this once. In my case XCode's settings in "Build Settings" -> "Code Signing" were "iOS Developer" in Release mode. Switching this manually to "iOS Distribution" fixed the issue.

**Comment by JaiKumarB** [comment]
I just noticed that for apps having extra scheme for watch app, Xcode 6.2 didn't have the ability to provide specific the provisioning profile for watch app scheme. This is enabled from 6.3 onwards. Updated xcode, pointed to specific provisioning profile and  it worked.

**Comment by alatyshev** [comment]
Is there any update on the issue? I was trying to use proposed workaround with  update_project_code_signing action, but this gives me Error setting value for option 'udid' even, though I see it gets correct value from SIGH_UDID.

**Comment by KrauseFx** [comment]
Code signing does work. Due to a bug in `xcodebuild` you'll need to set a static provisioning profile in your project settings. You can do so using the `update_project_provisioning` action.

Taken from the [Example MindNode Setup](https://github.com/fastlane/examples/blob/master/MindNode/Fastfile#L17-L40)

In your `Fastfile`: 

```ruby
  # Get the latest provisionnig profiles from the Dev Portal and 
  # update the project settings for each of the targets
  sigh(app_identifier: "com.mindnode.mindnodetouch.watchkitextension", output_path: "/tmp")
  update_project_provisioning(
    xcodeproj: project_file,
    build_configuration_filter: ".*WatchKit Extension.*"
  )

  sigh(app_identifier: "com.mindnode.mindnodetouch.watchkitapp", output_path: "/tmp")
  update_project_provisioning(
    xcodeproj: project_file,
    build_configuration_filter: ".*WatchKit App.*"
  )

  sigh(app_identifier: "com.mindnode.mindnodetouch", output_path: "/tmp")
  update_project_provisioning(
    xcodeproj: project_file,
    build_configuration_filter: "MindNodeTouch"
  )

  ipa(
    workspace: 'MindNode-iOS.xcworkspace',
    scheme: 'MindNode for iOS (Release)'
  )
```

This code downloads the latest provisioning profile and sets it for a specific target. This will work for WatchKit, Today Widgets and more.

**Comment by KrauseFx** [comment]
The `build_configuration_filter` defines the target name for which the provisioning profile should be set. It's a standard regex.

**Comment by yoiang** [comment]
@KrauseFx Attempting to use this method update_project_provisioning fails for me with
```
fastlane-1.3.2/lib/fastlane/actions/update_project_provisioning.rb:56:in `block in run': undefined method `build_configuration_list' for #<PBXObject:0x007fcebd8b8240> (NoMethodError)
	from fastlane-1.3.2/lib/fastlane/actions/update_project_provisioning.rb:44:in `each'
	from fastlane-1.3.2/lib/fastlane/actions/update_project_provisioning.rb:44:in `run'
	from fastlane-1.3.2/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from fastlane-1.3.2/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from fastlane-1.3.2/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from fastlane-1.3.2/lib/fastlane/fast_file.rb:93:in `chdir'
	from fastlane-1.3.2/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):24:in `build_app'
	from (eval):56:in `block (3 levels) in parse'
	from fastlane-1.3.2/lib/fastlane/runner.rb:35:in `call'
	from fastlane-1.3.2/lib/fastlane/runner.rb:35:in `block in execute'
	from fastlane-1.3.2/lib/fastlane/runner.rb:25:in `chdir'
	from fastlane-1.3.2/lib/fastlane/runner.rb:25:in `execute'
	from fastlane-1.3.2/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from fastlane-1.3.2/bin/fastlane:39:in `block (2 levels) in run'
	from commander-4.3.4/lib/commander/command.rb:178:in `call'
	from commander-4.3.4/lib/commander/command.rb:178:in `call'
	from commander-4.3.4/lib/commander/command.rb:153:in `run'
	from commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from fastlane-1.3.2/bin/fastlane:118:in `run'
	from fastlane-1.3.2/bin/fastlane:124:in `<top (required)>'
	from fastlane:23:in `load'
	from fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
@yoiang The easiest and most straight forward way is to update your project settings to define the provisioning profile to use.

**Comment by bryanchacosky** [comment]
@KrauseFx I ran into the same problem as @yoiang . I believe `update_project_provisioning` simply has a bug in the implementation. And unfortunately my build process includes regenerating the xcode project each time so changing a project setting manually isn't an option.

I solved the problem in my build process by replicating what `update_project_provisioning` is doing, and passing the extra build arguments into the `ipa` call.

```ruby
ipa(
  ...
  xcargs: "CODE_SIGN_RESOURCE_RULES_PATH='#{@xcode_sdk}/ResourceRules.plist' PROVISIONING_PROFILE='#{ENV["SIGH_UDID"]}'")```
  
where ``@xcode_sdk = `xcrun --sdk iphoneos --show-sdk-path`.strip``, and `sigh` must be called before this so that `SIGH_UDID` is set.

Hopefully it works for you, too!

**Comment by lyahdav** [comment]
FWIW I resolved this issue with https://github.com/KrauseFx/deliver/issues/118#issuecomment-97375854.

**Comment by frranck** [comment]
I had the same problem, not using fastlane but ipa build + deliver. I followed @KrauseFx tip to specify the provisioning profile in Build Settings/Code signing and it worked. :)

**Comment by ffittschen** [comment]
@lyahdav This helps indeed! But just like @bryanchacosky my XCode project is getting regenerated...

Is there any way to programmatically set the `Code Signing Identity > Release` to `iOS Distribution` ?

**Comment by KrauseFx** [comment]
@ffittschen I published a [Code Signing Guide](https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md) that helps you with setting up code signing for your project.

Also, I'm working on a new [tool](https://github.com/fastlane/gym) that will soon replace `shenzhen`. If you want, please try building your app with `gym` and let me know if that works for you :+1:

**Comment by ffittschen** [comment]
@KrauseFx I read your guide, but my `project.pbxproj` does not contain the `PROVISIONING_PROFILE = "";` part... It just appears if I manually switch from **Automatic** to something else and then back to **Automatic**

Is there already a fastlane action for gym? Or should I just use a shell command for now?

**Comment by KrauseFx** [comment]
@ffittschen There is no `fastlane` action *yet*, there will be one once `gym` is publicly announced.

**Comment by ajaybeniwal** [comment]
I am facing the same issue which deploying Ionic IOS app to test flight using FastLane 
{:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :IPA_OUTPUT_PATH=>"/Users/commonapp/Documents/OfficeWork/CAMobile/Ionic/CAMobileApp/CAMobileApp.ipa"}

I am using the below configuration 

gym(scheme: "CAMobileApp", project: "platforms/ios/CAMobileApp.xcodeproj")
 deliver(beta: true)

# deliver file 

beta_ipa "../CAMobileApp.ipa"

**Comment by ffittschen** [comment]
@ajaybeniwal if you specify the `output_directory` and the `output_name` in gym, you can remove the `beta_ipa` line from your `Deliverfile`. I followed the [Code Signing Guide](https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md) and set up my project like this:

### Ruby script, called between all cordova/ionic commands and the fastlane execution
```ruby
#!/usr/bin/env ruby

require 'xcodeproj'

path = ARGV.shift
xcproj = Xcodeproj::Project.open(path)
xcproj.build_settings('Release')['PROVISIONING_PROFILE'] = '$(PROFILE_UDID)'
```
### Fastfile
```ruby
lane :test do
    sigh
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    gym(
        project: 'testapp.xcodeproj',
        scheme: 'testapp',
        output_directory: '/Users/username/dev/testapp/artifacts/',
        output_name: 'testapp.ipa'
    )
    testflight(
        skip_deploy: true
    )
end
```

### Deliverfile
```ruby
# empty, everything done in the Fastfile
```
