### ISSUE TITLE
deliver should retry if transport had errors

### ISSUE THREAD

**Issue by alistra** [fastlane/deliver#150]
INFO [2015-03-24 21:09:02.33]: This might take a few minutes, please don't interrupt the script
    INFO [2015-03-24 21:09:02.34]: Waiting for iTunes Connect transporter to be finished.
    INFO [2015-03-24 21:09:02.34]: iTunes Transporter progress... this might take a few minutes...
    ERROR [2015-03-24 21:22:03.21]: [Transporter Error Output]: An error occurred while uploading a file to Apple's remote server.
    ERROR [2015-03-24 21:22:03.21]: [Transporter Error Output]: An exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.

    INFO [2015-03-24 21:25:14.18]: iTunes Transporter successfully finished its job
    ERROR [2015-03-24 21:25:14.32]: An error occurred while uploading a file to Apple's remote server.
    An exception has occurred: The transport has been detected as having stalled and has been aborted.  Please try again.
    /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.8.0/lib/deliver/deliver_process.rb:267:in `trigger_metadata_upload': Error uploading app metadata (RuntimeError)
        from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.8.0/lib/deliver/deliver_process.rb:51:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.8.0/lib/deliver/deliverer.rb:132:in `finished_executing_deliver_file'
        from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.8.0/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
        from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.8.0/lib/deliver/deliverer.rb:84:in `new'
        from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.8.0/lib/deliver/deliverer.rb:84:in `initialize'
        from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.8.0/bin/deliver:36:in `new'
        from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.8.0/bin/deliver:36:in `block (3 levels) in run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.8.0/bin/deliver:32:in `chdir'
        from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.8.0/bin/deliver:32:in `block (2 levels) in run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.0/lib/commander/command.rb:154:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.0/lib/commander/runner.rb:421:in `run_active_command'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.0/lib/commander/runner.rb:81:in `run!'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.0/lib/commander/delegates.rb:15:in `run!'
        from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.8.0/bin/deliver:86:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.8.0/bin/deliver:99:in `<top (required)>'
        from /usr/local/bin/deliver:23:in `load'
        from /usr/local/bin/deliver:23:in `<main>'

If we can detect that there was some connection error, why not try to retry a few times?

**Comment by KrauseFx** [comment]
The transporter automatically retries up to 3 times. Did it stop immediately without retrying? If so, why did an error occur? Is the connection unstable or was there a firewall causing this?

**Comment by alistra** [comment]
The error only showed once (no idea if it retried 3 times on backend). 

This was during normal internet activity, i was uploading like 10 batches of screenshots in a row and one failed like this, other went through normally. The network was working on other apps/utils etc.

Maybe some temporary itc connection issue?

**Comment by ben-lings-tessella** [comment]
I've seen this happen where deliver interprets one of the failures-with-automatic-retry that iTMSTransporter does as an overall failure. Possibly related is that the times I've seen this has been when building and uploading with Xcode 6.2, which has an older version of iTMSTransporter to Xcode 6.3. Some of the log output is different between the versions.
