### ISSUE TITLE
Parallel uploads might fail due to temp file

### ISSUE THREAD

**Issue by theoriginalgri** [fastlane/deliver#194]
Today I started up my Jenkins to build new versions for my apps. To my surprise, two of them failed with strange errors.

The first one (app1):
```
+ deliver testflight app1.ipa
/tmp/deploytmp.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “deploytmp.plist” couldn’t be opened because there is no such file." UserInfo=0x7fa1014140e0 {NSFilePath=/tmp/deploytmp.plist, NSUnderlyingError=0x7fa101413e50 "The operation couldn’t be completed. No such file or directory"})
Could not automatically find the app identifier, please enter the app's bundle identifier: 
```

The second one (app2):
```
[31mERROR [2015-05-06 10:17:34.04]: [0m[31m[Transporter Error Output]: ERROR ITMS-90053: "This bundle is invalid. The bundle identifier is already in use by a different software package."
[0m
[31mERROR [2015-05-06 10:17:34.04]: [0m[31m[Transporter Error Output]: ERROR ITMS-90055: "The bundle identifier cannot be changed from the current value, 'de.company.app1'. If you want to change your bundle identifier, you will need to create a new application in iTunes Connect."
```

After looking at the source of deliver I found that it creates "/tmp/deploytmp.plist" and reads it using the plistutil. When this is done by two or more builds in parallel, a race condition occurs and the build of app2 thinks it's actually uploading app1. The upload of app2 also deleted the file before the upload of app1 was able to parse it itself :(

A solution to this might be to include the ipa name in the temporary file name. I would fix this myself but I don't have any ruby experience.

Reference: https://github.com/KrauseFx/deliver/blob/6222f085ad7319649ec96062002cb623a65e4f13/lib/deliver/ipa_file_analyser.rb#L25

**Comment by KrauseFx** [comment]
Oh, this is a good point. Actually, all `fastlane` tools are designed to **not** run in parallel. For example `snapshot` uses the simulator. 

I guess I should go through all tools, decide if parallel execution should be possible. If it's not, I'll implement some lock mechanism so only one instance is running at the same time.

**Comment by hiltonc** [comment]
I've hit this problem a lot, too. Jenkins job timings.

**Comment by KrauseFx** [comment]
In the mean time, you'll have to configure Jenkins so that the `deliver` job is only executed one time in parallel.

**Comment by hiltonc** [comment]
As a workaround, I'm now using this wherever I use `deliver` in Jenkins:

    lockfile -l600 /tmp/deliver.lock
    deliver ...
    rm -f /tmp/deliver.lock
