### ISSUE TITLE
--deliverfile option?

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/deliver#232]
is there a way to call deliver with a deliverfile option?
I have one project with targets that build to three apps. I'd like to be able to write 

  deliver --deliverfile ./deliver/deliverfile-paid

snapshot has this, but I can't find it for deliver.

thanks.

**Comment by KrauseFx** [comment]
That option is not available. If you use `fastlane` you can however specify the path containing the `Deliverfile` using `deliver_file_path`.
