### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by gfpacheco** [fastlane/deliver#266]
I have a fastlane project set up and it was working fine until last week.
Today I was prompted to update fastlane, after that the deliver action is always saying it couldn't find Apple ID and when I tell the number it crashes with the folowing error:

    [14:13:55]: ---------------------
    [14:13:55]: --- Step: deliver ---
    [14:13:55]: ---------------------
    [14:13:56]: Skipping submission of app update
    [14:13:56]: Got all information needed to deploy a new update ('1.0') for app 'XXX'
    [14:13:57]: App doesn't seem to be in the App Store yet or is not available in the US App Store. Using the iTC API instead.
    [14:13:57]: Could not find Apple ID based on the app identifier in the US App Store. Maybe the app is not yet in the store?
    [14:13:57]: You can provide the Apple ID of your app using `apple_id '974739333'` in your `Deliverfile`

    Apple ID of your app (e.g. 284882215): XXX
    [14:16:14]: Variable Dump:
    [14:16:14]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios publish", :PRODUCE_APPLE_ID=>"XXX", :SIGH_PROFILE_PATH=>"XXX/AppStore_XXX.mobileprovision", :SIGH_UDID=>"667fe9d1-1c80-4a9f-8cda-5355a96a6dc3", :IPA_OUTPUT_PATH=>"XXX/Distribution.ipa", :DSYM_OUTPUT_PATH=>"XXX/Distribution.app.dSYM.zip"}
    [14:16:14]: Broken pipe
    [14:16:15]: fastlane finished with errors
    /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:62:in `write': Broken pipe (Errno::EPIPE)
    	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:62:in `write'
    	from /Library/Ruby/Gems/2.0.0/gems/websocket-driver-0.6.0/lib/websocket/driver/server.rb:60:in `write'
    	from /Library/Ruby/Gems/2.0.0/gems/websocket-driver-0.6.0/lib/websocket/driver/draft75.rb:75:in `frame'
    	from /Library/Ruby/Gems/2.0.0/gems/websocket-driver-0.6.0/lib/websocket/driver.rb:102:in `text'
    	from /Library/Ruby/Gems/2.0.0/gems/websocket-driver-0.6.0/lib/websocket/driver/server.rb:28:in `block (2 levels) in <class:Server>'
    	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:84:in `send'
    	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/server.rb:33:in `send'
    	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/browser.rb:270:in `command'
    	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/browser.rb:212:in `set_headers'
    	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/driver.rb:190:in `headers='
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.10.1/lib/fastlane_core/itunes_connect/itunes_connect.rb:60:in `initialize'
    	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/app.rb:77:in `new'
    	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/app.rb:77:in `itc'
    	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/app.rb:152:in `create_new_version!'
    	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:210:in `verify_app_on_itunesconnect'
    	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:38:in `run'
    	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:133:in `finished_executing_deliver_file'
    	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
    	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `new'
    	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `initialize'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/actions/deliver.rb:21:in `new'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/actions/deliver.rb:21:in `block in run'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/actions/deliver.rb:17:in `chdir'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/actions/deliver.rb:17:in `run'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/fast_file.rb:114:in `block (2 levels) in method_missing'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/fast_file.rb:96:in `block in method_missing'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/fast_file.rb:95:in `chdir'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/fast_file.rb:95:in `method_missing'
    	from (eval):59:in `block (3 levels) in parse'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/runner.rb:39:in `call'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/runner.rb:39:in `block in execute'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/runner.rb:29:in `chdir'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/runner.rb:29:in `execute'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/bin/fastlane:39:in `block (2 levels) in run'
    	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
    	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
    	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
    	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/bin/fastlane:128:in `run'
    	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.7.3/bin/fastlane:134:in `<top (required)>'
    	from /usr/bin/fastlane:23:in `load'
    	from /usr/bin/fastlane:23:in `<main>'

My lane use this tool sequence:

    produce(...)
    sigh
    ipa(...)
    resign(...)
    deliver(force: true, skip_deploy: true)

If I comment the other commands and add `ipa('../Distribution.ipa')` to Deliverfile it works fine.
Any clues?

**Comment by KrauseFx** [comment]
That seems to be an internet connection error. Can you try running it from a different connection?

**Comment by gfpacheco** [comment]
I tried a few times without success. When I left the deliver step alone it worked. Gonna try again tomorrow, thanks.

**Comment by gfpacheco** [comment]
The error changed, it now can find the Apple ID but fails with the same `Connection reset by peer` error as https://github.com/fastlane/PEM/issues/58. It's just so weird that it only happens when I run the complete lane, but doesn't if I run only the desired action.

**Comment by milch** [comment]
I had a similar issue where `cert` stopped working when run in a complete lane, but worked fine by itself. The issue resolved itself after some time, so I didn't get to do any more debugging.

Alternatively, you could try setting up a fresh `ruby`, see if maybe one of your other gems causes those problems:
```sh
brew install rbenv ruby-build

# make sure to follow the instructions that brew gives you and also put this in your ~/.bashrc
eval "$(rbenv init -)"

# install ruby version 2.2.2, activating it globally and making your tools available in the current shell
rbenv install 2.2.2
rbenv global 2.2.2
rbenv rehash

gem install fastlane cocoapods #... and all the other tools you need

# rehash again to make your tools available
rbenv rehash
```

After that, run `fastlane` again and see if the problem persists.

**Comment by nklausni** [comment]
I also got the problem of gfpacheco. Also with "Connection reset by peer" error.

It only happens when running it as a complete lane.

**Comment by KrauseFx** [comment]
@nklausni Did you try following the great guide by @milch?

**Comment by gfpacheco** [comment]
I tried, no luck with a fresh install of Ruby (I used RVM for doing so). Still getting `Connection reset by peer`

**Comment by nklausni** [comment]
@KrauseFx i followed all the steps from this guide but it didn't helped me out. Same problem

```
[11:24:51]: Connection reset by peer - recvfrom(2)
[11:24:51]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:73:in `recv': Connection reset by peer - recvfrom(2) (Errno::ECONNRESET)
	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:73:in `receive'
	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:85:in `send'
	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/server.rb:33:in `send'
	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/browser.rb:270:in `command'
	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/browser.rb:212:in `set_headers'
	from /Library/Ruby/Gems/2.0.0/gems/poltergeist-1.5.1/lib/capybara/poltergeist/driver.rb:190:in `headers='
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.10.1/lib/fastlane_core/itunes_connect/itunes_connect.rb:60:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/app.rb:77:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/app.rb:77:in `itc'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/app.rb:152:in `create_new_version!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:210:in `verify_app_on_itunesconnect'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliver_process.rb:38:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:133:in `finished_executing_deliver_file'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverfile/deliverfile.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/deliverer.rb:85:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/actions/deliver.rb:21:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/actions/deliver.rb:21:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/actions/deliver.rb:17:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/actions/deliver.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/fast_file.rb:117:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/fast_file.rb:103:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/fast_file.rb:102:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/fast_file.rb:102:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/fast_file.rb:135:in `method_missing'
	from (eval):181:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/runner.rb:40:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/runner.rb:40:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/runner.rb:30:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/runner.rb:30:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.8.0/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

**Comment by shoshRose** [comment]
I have the same issue (just upgraded to fastlane 1.13.0), everything runs well for the following:
```
produce
pem
cert
sigh
```
Once I add deliver to the lane I get the error:
```
produce
pem
cert
sigh
deliver
Connection reset by peer - recvfrom(2) (Errno::ECONN RESET)
``` 
Any ideas?

**Comment by pedro380085** [comment]
Same error here, when I upload the app on the first time, I also get:

```
You can provide the Apple ID of your app using `apple_id '974739333'` in your `Deliverfile`
```

**Comment by fatuhoku** [comment]
What's the latest on this? I've relied on setting

```ruby
  app_identifier "my.apps.identifier"
```

in the `Appfile`, which has worked for me fairly well so far. However now I consistently get asked about the app id.

**Comment by KrauseFx** [comment]
@fatuhoku Please share your output when getting asked for the App ID.
