### ISSUE TITLE
Deliver sits waiting indefinitely for app processing, when app is in an "Invalid Binary" state

### ISSUE THREAD

**Issue by andrewpage** [fastlane/deliver#280]
**iTunes Connect for the last 15 or so minutes:**
<img width="1049" alt="processing" src="https://cloud.githubusercontent.com/assets/3052811/8881748/e9166324-31f6-11e5-9dab-63c8aa7f537d.png">

**Latest from Fastlane Deliver:**
```
[11:41:18]: Sorry, we have to wait for iTunesConnect, since it's still processing the uploaded ipa file
If this takes longer than 45 minutes, you have to re-upload the ipa file again.
You can always open the browser page yourself: 'https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/10000*****/pre/builds'
Passed time: ~24 minute(s)
```

Deliver isn't detecting that the app deployment failed. Not sure why this is?

**Comment by KrauseFx** [comment]
Sorry, `deliver` was not yet updated to `spaceship` and so it can't get further details for the builds.
