### ISSUE TITLE
Feature request: custom 'License Agreement'

### ISSUE THREAD

**Issue by shoshRose** [fastlane/deliver#283]
Same as ratings configuration works. receives a json file with the agreement text and list of territories.
@KrauseFx What do you think?

**Comment by KrauseFx** [comment]
I have never needed this myself, I don't really know any details about this process.

**Comment by shoshRose** [comment]
Its a way to write your own terms of use. (usually necessary for companies rather than private people)  It only has 2 steps. (screenshot attached)
I'm trying to add it myself using your 'itunes_connect_app_rating.rb' as reference. but i have limited experience with ruby. 
Do you think you'll have time to add this feature?

![a](https://cloud.githubusercontent.com/assets/10708301/8933668/c788a88a-354c-11e5-972c-89dfa77cac52.png)

**Comment by KrauseFx** [comment]
Sorry, there are no plans to implement this feature right now. Also, I'm currently in the process of upgrading `deliver` to use the new `spaceship`: https://github.com/KrauseFx/deliver/pull/259

**Comment by shoshRose** [comment]
Ohh.. too bad. I'm still using the good old fastlane :)

**Comment by flipdish** [comment]
We'd love this feature also.
