### ISSUE TITLE
Failed to Submit

### ISSUE THREAD

**Issue by adytzs** [fastlane/deliver#285]
After update fastlane and another tools, I got this error every I submit.

![untitled](https://cloud.githubusercontent.com/assets/1079533/8946517/36f5df3a-35bb-11e5-8682-928971955495.png)

anyway, I change some data on fastlane file, for "produce" function. just remove "produce_" tag

**Comment by dangthaison91** [comment]
I have same problem. Also update Deliver, Produce manual but i still get this error.

Other question: I update fastlane but deliver, produce... does not get update?

**Comment by KrauseFx** [comment]
To update individual tools just run 
`sudo gem update produce`
`sudo gem update deliver`

This error is probably related to the down time of iTunes Connect.

**Comment by dangthaison91** [comment]
I had tried many times and also check iTunes Connect site, it still alive, at this time. Version 1.12 run normally.
