### ISSUE TITLE
Upload only description, changelog for app "Pending release"

### ISSUE THREAD

**Issue by bvirlet** [fastlane/deliver#287]
Hi Felix. 

I'm not clear if this is possible without using the Ruby API but I have an app 'Pending release' and I would  like to update the following metadata: description and changelog from the `metadata/` folder. However, it seems the script fails because I have local changes to the keywords files too, and they can't be changed under the 'Pending release' status. Is there any way to ignore those changes to the keywords and just update the description and what's new?

Thanks!

**Comment by KrauseFx** [comment]
@bvirlet That's currently not possible using `deliver`, but you can use the [spaceship](https://spaceship.airforce) API directly. 

Take a look at [this](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/set_changelog.rb). Basically you could use the same code and set the description and other information too :+1:

**Comment by bvirlet** [comment]
Thanks, Felix. I will try that.

(I actually just saw `App Status 'pendingDeveloperRelease' not yet implemented, please submit an issue on GitHub` in the logs.)

**Comment by KrauseFx** [comment]
Oh, great, thanks, I'll fix this! :+1:
