### ISSUE TITLE
How to setup DELIVER_WHAT_TO_TEST?

### ISSUE THREAD

**Issue by skywinder** [fastlane/deliver#290]
There is no description, how to setup this variable automatically. (ok, I can set it by export manually, but it's not very convenient).

I found, that fastlane use dotenv
Here is my `.env` file placed in `./faslane` folder:

```
DELIVER_BETA_DESCRIPTION="My Beta Description"
DELIVER_WHAT_TO_TEST="Try the brand new project button"
DELIVER_BETA_FEEDBACK_EMAIL="mymail@fff.com"
```
But deliver got's output in the end:

>DELIVER_WHAT_TO_TEST: ''
DELIVER_BETA_DESCRIPTION: ''
DELIVER_BETA_FEEDBACK_EMAIL: ''
Successfully distributed latest beta build 🚀

( actually, it  doesn't distributed, but it's other issue #289 )

**Comment by besi** [comment]
I am wondering. Is `DELIVER_WHAT_TO_TEST` the equivalent of the file `fastlane/metadata/version_whats_new.txt`?

**Comment by KrauseFx** [comment]
@besi Sorry no. The `version_whats_new.txt` is the change-log for the app in the App Store.

**Comment by bassrock** [comment]
@KrauseFx is there an equivalent metadata filename for the metadata folder for WHAT_TO_TEST? It looks like description and feedback_email exist.

**Comment by KrauseFx** [comment]
@bassrock Sorry, not right now.
