### ISSUE TITLE
Feature: Screenshots downloading progress

### ISSUE THREAD

**Issue by bartl-git** [fastlane/deliver#296]
Is it posible to show screenshots downloading progress?
E.g. something like this: Downloading existing screenshot (100 of 350) '2_iphone35_3_iphone4_ru.jpg' of device type: 'iphone35'

**Comment by KrauseFx** [comment]
@bartl-git Sure, that would be possible. I'm currently in the process of re-writing this part using `spaceship`.

Why would you need this feature?

**Comment by bartl-git** [comment]
I am currently downloading screenshots from series of our projects. Each have 15 localisations. And I want to know when downloading will finish.

**Comment by bartl-git** [comment]
Showing estimated time will be great feature too, if it's possible
