### ISSUE TITLE
"deliver upload_metadata" doesn't create new version

### ISSUE THREAD

**Issue by bartl-git** [fastlane/deliver#298]

**Comment by KrauseFx** [comment]
Why should it create a new version? How should `deliver` know which version to create?

**Comment by bartl-git** [comment]
I think "upload_metadata" uses Deliverfile, isn't it?
Now if I use deliver without options and do not provide any ipa file, it works as I expected: creates new version and upload new metadata.

**Comment by KrauseFx** [comment]
I just pushed [deliver 1.0.0](https://github.com/KrauseFx/deliver/releases/tag/1.0.0) and [fastlane 1.30.0](https://github.com/KrauseFx/fastlane/releases/tag/1.30.0). Please update using `sudo gem update fastlane` and let me know if everything works for you.

Also, make sure to follow the new [Migration Guide to 1.0](https://github.com/KrauseFx/deliver/blob/master/MigrationGuide.md).

Check out `deliver --help` for the new options, as you can now skip the binary upload.

**Comment by KrauseFx** [comment]
Let me know if you have any questions.
