### ISSUE TITLE
Existing screenshots sometimes is not downloaded properly

### ISSUE THREAD

**Issue by bartl-git** [fastlane/deliver#300]
There is black areas at the bottom of screenshots.

I attach one such file as example.

![0_ipad_free_ipad_1_en](https://cloud.githubusercontent.com/assets/1385441/9156567/cd7c5940-3ee7-11e5-8d8b-ee5d0888340a.jpg)

May be it's not issue of `deliver`, but it will be great if `deliver` would check that file is downloaded properly and download again the file if something wrong happened.

**Comment by SPAHI4** [comment]
have this issue too
