### ISSUE TITLE
How to change IDFA value to 'Yes' using Deliver in final step of submit for review?

### ISSUE THREAD

**Issue by Srthk** [fastlane/deliver#306]
By default the options after "Submit For Review" are select as "No" by Fastlane/Deliver. I would like to change or set the values of 'Content Rights' and 'Advertising Identifier' using either my deliverfile or fastfile. How can I achieve that?

The error generated after `deliver` is this- 

![error1439624560](https://cloud.githubusercontent.com/assets/7152922/9288049/57c80eec-4351-11e5-841f-173b35f4ff74.png)

**Comment by KrauseFx** [comment]
I'm working no a re-write of `deliver` using `spaceship`, you can follow the progress here: https://github.com/KrauseFx/deliver/pull/259

**Comment by KrauseFx** [comment]
Check out https://github.com/KrauseFx/deliver/releases/tag/1.0.0.beta and let me know if that works for you :+1:
