### ISSUE TITLE
Use same screenshots for all languages

### ISSUE THREAD

**Issue by osmanertem** [fastlane/deliver#308]
Hi,
Thank you for developing great tools like deliver. I really appreciate it.

I have a question/request for you.

In itunesconnect web interface, default language's screenshots may be used for other languages too. You dont need to upload same screenshots for all languages. 

But in deliver, I had to specify screenshots folder for all languages. It uploads them all one by one. This upload process is a waste of time for me. 

Is it possible to use same screenshot ( and upload only once) for all languages?

Thank you.

**Comment by KrauseFx** [comment]
Sorry, that's not possible right now. To be honest, I didn't know that's possible on iTunes Connect.

**Comment by madangosain** [comment]
If you don't want to maintain multiple folders, create symlinks pointing to one folder for each language. It'll upload same photos for all language

**Comment by osmanertem** [comment]
hi madangosain,
Thank you for your answer.
I do the same thing(creating symbolic links) but, it increases the upload time as expected. 
I wanted to skip upload process for each language.

**Comment by dral3x** [comment]
I think you cannot skip the uploads on each languages. I have apps with multiple languages and if I want to update screenshots for the "base" language, I also have to upload all the others. Cannot be done automatically in iTC.

**Comment by lacostej** [comment]
What osmanertem means if that on ITC, if you create a new language, by default, it will use the screenshots for the default language.

This is rather useful. I'll see how this is implemented under the hood (i.e. does ITC copy the screenshots or jut keep the fields blanks). deliver shouldn't force the user to add those screenshots.
