### ISSUE TITLE
Deliver is changing $stdout to STDOUT

### ISSUE THREAD

**Issue by andrewpage** [fastlane/deliver#313]
Encountered an issue with deliver recently. I'm using the exposed deliver Ruby classes, and in my project I'm setting `$stdout` to a custom class to redirect output. This works fine with TestFlight delivery, but for some reason, `$stdout` is getting reset back to `STDOUT` (`#<IO:<STDOUT>>`) during the App Store delivery process.

```
> puts $stdout.inspect
#<MyProject::CustomOutput:0x007fabe1963888>
> app = Deliver::App.new(app_identifier: bundle_id, apple_id: @app_id)
> uploader = Deliver::IpaUploader.new(
    app,
    TMP_DIRECTORY,
    @ipa,
    Deliver::IPA_UPLOAD_STRATEGY_APP_STORE
)
> uploader.upload!
> puts $stdout.inspect
#<IO:<STDOUT>>
```

Can you think of any reason why `$stdout` would be reset back to STDOUT? Any why its only happening in AppStore delivery? I was able to work around this (by storing a reference to the instance of my custom output and explicitly setting `$stdout` to that stored reference after the `upload!`, but I'd rather see this fixed in FastlaneCore/Deliver (unless, of course, `$stdout` is being changed for a valid reason).

**Comment by KrauseFx** [comment]
You submitted a pull request a while back that changes this behaviour: https://github.com/fastlane/fastlane_core/pull/22

I don't know more about this, I'd have to look into this, sorry.

**Comment by andrewpage** [comment]
Yes, but that shouldn't be redefining $stdout itself, just changing the output where Fastlane tools send their logs. I've done some code searches within both deliver and fastlane_core, but I haven't found anything promising just yet.

Besides those two repositories, do you know of any more libraries that deliver is using internally that I should be looking through?

**Comment by KrauseFx** [comment]
Sure:

`commander` and with it `highline`

Besides that, almost all outputs in `fastlane` are done via `FastlaneCore::Helper.log.info "text"`
