### ISSUE TITLE
Support app video

### ISSUE THREAD

**Issue by vytis** [fastlane/deliver#34]
At the moment the video uploaded manually to iTunes Connect just gets deleted after running `deliver`

**Comment by fatuhoku** [comment]
:+1: this would be would be incredible — although if it's large it probably isn't something you want to be doing on every deploy.

**Comment by KrauseFx** [comment]
This is actually possible using `spaceship` thanks to @lacostej, but not implemented in `deliver`. 

@lacostej how much work is it to add this feature?

**Comment by lacostej** [comment]
@KrauseFx @fatuhoku @cannyboy uploading videos should very easy to integrate. 

This was my test code:
```
trailers = appv.raw_data['details']['value'][0]['appTrailers']['value']

videos = [
  [:ipad,        'preview_1200.mov', '10.00'],
  [:iphone6Plus, 'preview_1080.mov', '15.00'],
  [:iphone6,     'preview_1334.mov', '20.00'],
  [:iphone4,     'preview_1136.mov', '25.00']
]

videos.each { |a|
  device = a[0]
  file = a[1]
  timestamp = a[2]
  puts "Uploading #{file} for #{device} with timestamp #{timestamp}"
  appv.upload_video!(nil, language, device, timestamp) unless trailers[device.to_s]['value'].nil?
}
appv.save!
```

Integration into deliver should be very easy. You need to allow for the user to specify the preview screenshot and/or the timestamp. The upload_video! method should be documented enough.

As you have guessed, I don't have time to deal with this right now. But soon :)

**Comment by KrauseFx** [comment]
Thanks @lacostej, this helps a lot. I'm more than happy to merge a pull request adding this functionality :+1:

**Comment by shaps80** [comment]
Just wondering what the status is for this? 

Was just setting up Deliver and realised I need this functionally ;)

**Comment by srudoi** [comment]
Would be great to get some update on this! It is a needed functionality indeed.

**Comment by KrauseFx** [comment]
This feature is currently not in development. I'm more than happy to merge a pull request adding this functionality :+1:
