### ISSUE TITLE
 Spaceship::TunesClient::ITunesConnectError in 1.0.0 beta3

### ISSUE THREAD

**Issue by The-Guru** [fastlane/deliver#348]
Hi there,

I would like to thank you personally for this amazing tool that you have created and save us a lot of time!

So it seems there is a problem when updating screenshots for a language that it is already created in iTunes Connect. So I have tested with the same langue (de-DE), the first time deliver created the language and uploaded the screenshots perfectly but doing the same thing again deliver failed when "saving changes" appeared of the console with this error message: 

```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Spaceship::TunesClient::ITunesConnectError
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/tunes_client.rb:275:in `update_app_version!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/app_version.rb:265:in `save!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/lib/deliver/upload_screenshots.rb:43:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/lib/deliver/runner.rb:53:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/lib/deliver/runner.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/lib/deliver/commands_generator.rb:84:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.0.0.beta3/bin/deliver:5:in `<top (required)>'
	from /usr/bin/deliver:23:in `load'
	from /usr/bin/deliver:23:in `<main>'
```

I hope you can fix this problem before the 1.0.0 release :+1: 

Update: I'm using Xcode 6.4

Thanks.
Best,

Óscar

**Comment by KrauseFx** [comment]
> I would like to thank you personally for this amazing tool that you have created and save us a lot of time!

Thanks! :smile: 

Could you try using the language code `de` instead of `de-DE`?

**Comment by The-Guru** [comment]
Hi Felix,

I used de-DE because is the language definition for German which appers in the deliver documentation. I will try it again tomorrow.

Also.. Is there any problem using XCode 6.4 command line tools with the new deliver or should I install XCode 7?

**Comment by KrauseFx** [comment]
I just pushed [deliver 1.0.0](https://github.com/KrauseFx/deliver/releases/tag/1.0.0) and [fastlane 1.30.0](https://github.com/KrauseFx/fastlane/releases/tag/1.30.0). Please update using `sudo gem update fastlane` and let me know if everything works for you.
Also, make sure to follow the new [Migration Guide to 1.0](https://github.com/KrauseFx/deliver/blob/master/MigrationGuide.md).

It might not solve your issue, but please try to update anyway and let me know if it helps.

**Comment by mikefranken** [comment]
I have similar issues with it-IT, after renaming the directory in fastlane/metadata to it, it works. Can you please support it-IT?

**Comment by mikefranken** [comment]
And it goes wrong eventually:

[19:48:23]: Uploading './fastlane/screenshots/fr-FR/fr-FR-iPhone6Plus-1-Login-portrait.png'...
[19:48:26]: Uploading './fastlane/screenshots/fr-FR/fr-FR-iPhone6Plus-2-Dashboard-portrait.png'...
[19:48:29]: Uploading './fastlane/screenshots/fr-FR/fr-FR-iPhone6Plus-3-StatsView-portrait.png'...
[19:48:33]: Uploading './fastlane/screenshots/fr-FR/fr-FR-iPhone6Plus-4-Switches-portrait.png'...
[19:48:39]: Uploading './fastlane/screenshots/fr-FR/fr-FR-iPhone6Plus-5-Sensors-portrait.png'...
[19:48:43]: Uploading './fastlane/screenshots/it-IT/it-IT-iOS-iPad-0-LandingScreen-portrait.png'...
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.11.1/lib/spaceship/tunes/app_version.rb:489:in `container_data_for_language_and_device': it-IT isn't an activated language (RuntimeError)
	from /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.11.1/lib/spaceship/tunes/app_version.rb:477:in `screenshots_data_for_language_and_device'
	from /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.11.1/lib/spaceship/tunes/app_version.rb:340:in `upload_screenshot!'
	from /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deliver-1.1.3/lib/deliver/upload_screenshots.rb:36:in `block in upload'

**Comment by mikefranken** [comment]
renaming the screenshot dir as well helps:
[20:03:43]: Uploading './fastlane/screenshots/it/it-IT-iOS-iPad-0-LandingScreen-portrait.png'...
[20:05:57]: Uploading './fastlane/screenshots/it/it-IT-iPhone4-1-Login-portrait.png'...
[20:05:59]: Uploading './fastlane/screenshots/it/it-IT-iPhone4-2-Dashboard-portrait.png'...

**Comment by mikefranken** [comment]
arghhh:
[20:08:20]: Uploading './fastlane/screenshots/it/it-IT-iPhone6-3-StatsView-portrait.png'...
[20:08:27]: Uploading './fastlane/screenshots/it/it-IT-iPhone6-4-Switches-portrait.png'...
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:182:in `sysread_nonblock': Connection reset by peer (Faraday::ConnectionFailed)
	from /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:182:in `read_nonblock'
	from /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
	from /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
	from /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
	from /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'

**Comment by KrauseFx** [comment]
@mikefranken That's an iTunes Connect server error. It will also happen when manually uploading the screenshots to iTunes Connect directly.

**Comment by mikefranken** [comment]
Yeah, you're right. It goes much easier with deliver than by hand. Still a shame of course that deliver stops and I have to start all over again, hoping not to get a time out next time.

**Comment by KrauseFx** [comment]
What do you mean start all over again? All you have to do is run `deliver` from the command line, right? Not much time lost :wink:

**Comment by mikefranken** [comment]
From the command line, yes. So meanwhile I can do something else ;-) 
Takes more than 6 minutes in my case, and only succeeded the 4th attempt. 5 languages, 5 devices, 5 screens.

**Comment by mikefranken** [comment]
Don't get me wrong, your tools are great!

**Comment by mikefranken** [comment]
But frustrating it can be:
[20:36:41]: Uploading './fastlane/screenshots/nl-NL/nl-NL-iPhone6Plus-4-Switches-portrait.png'...
[20:36:48]: Uploading './fastlane/screenshots/nl-NL/nl-NL-iPhone6Plus-5-Sensors-portrait.png'...
[20:36:51]: Saving changes
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.11.1/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Unauthorized access (Spaceship::TunesClient::ITunesConnectError)

**Comment by mikefranken** [comment]
[21:13:51]: Saving changes
[21:15:16]: Successfully uploaded screenshots to iTunes Connect
[21:15:19]: Finished the upload to iTunes Connect

**Comment by KrauseFx** [comment]
Yes, really sorry about that. I hope Apple resolves their server issues today/tomorrow :+1:

**Comment by mikefranken** [comment]
No need to be sorry. Would it be an idea to upload the images in smaller 'batches', say, per language?

**Comment by The-Guru** [comment]
Yeah! Is a pain in the ass when you are uploading 20 images per language for 16 languages and then it fails in the 15th! Could you commit every language ?

**Comment by mikefranken** [comment]
Eventually yes!

**Comment by KrauseFx** [comment]
@mikefranken I like the idea. But it wouldn't really solve the problem as you have to re-run `deliver` when it fails, right? Or does it automatically start again when something fails?

**Comment by jstart** [comment]
Seeing a similar error... are any of these languages unsupported?

Activating languages cmn-Hans, cmn-Hant, da-DK, de-DE, el-GR, en-AU, en-CA, en-GB, en-US, es-ES, es-MX, fi-FI, fr-CA, fr-FR, id-ID, it-IT, ja-JP, ko-KR, ms-MY, nl-NL, no-NO, pt-BR, pt-PT, ru-RU, sv-SE, th-TH, tr-TR, vi-VI...
/Users/ctruman/.rvm/gems/ruby-2.1.2/gems/spaceship-0.11.2/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Spaceship::TunesClient::ITunesConnectError
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/spaceship-0.11.2/lib/spaceship/tunes/tunes_client.rb:278:in `update_app_version!'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/spaceship-0.11.2/lib/spaceship/tunes/app_version.rb:265:in `save!'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/deliver-1.3.0/lib/deliver/upload_metadata.rb:84:in `verify_available_languages!'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/deliver-1.3.0/lib/deliver/upload_metadata.rb:21:in `upload'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/deliver-1.3.0/lib/deliver/runner.rb:52:in `upload_metadata'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/deliver-1.3.0/lib/deliver/runner.rb:20:in `run'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/deliver-1.3.0/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/deliver-1.3.0/lib/deliver/commands_generator.rb:84:in `run'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/deliver-1.3.0/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/gems/deliver-1.3.0/bin/deliver:5:in `<top (required)>'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/bin/deliver:23:in `load'
	from /Users/ctruman/.rvm/gems/ruby-2.1.2/bin/deliver:23:in `<main>'
