### ISSUE TITLE
In app purchases upload

### ISSUE THREAD

**Issue by vytis** [fastlane/deliver#35]
It would useful be very useful to have support for in app purchases. At the moment these have to be submitted separately from the rest of the app metadata.

**Comment by stonemonk** [comment]
It would be extremely useful to us as well to be able to programmatically add/update IAPs from the ruby Deliverfile.  (Need to add 50 IAPs to an app, loading all localizations from a separate yaml file.)

Maybe this is supported already, but I didn't see it in the documentation.  To be clear, I am requesting a method be added so for example in the Deliverfile, I can do something like this:

iap({
  "reference-name" => "Some Upgrade",
  "product-id" => "com.company.product",
  "type" => "non-consumable",
  "price-tier" => "1",
  "localizations" => {
    "en-US" => { "title" => "EN Title",  "description" => "EN Description"},
  }
})

where it will add/update the IAP with given product id and info, and can be called multiple times for each IAP I want to add/update.

**Comment by KrauseFx** [comment]
This feature is not available in `deliver`. It would be possible to add the new options to the `Deliverfile` and fill in the data into the `metadata.xml`.

**Comment by stonemonk** [comment]
Yea thats what I suspected. I would be happy to add the support myself, but I've never used Ruby before.  Looking into Ruby now and at the Deliver code, but I am not really getting it :(   Any chance you would have time to implement it?

**Comment by victorfigol** [comment]
This is an important missing feature from deliver,

Sonotap would like to sponsor it.

**Comment by czechboy0** [comment]
+1

**Comment by carles** [comment]
Yes, this feature would be quite nice to have

**Comment by lucaquerella** [comment]
+1, this would be great

**Comment by facundomedica** [comment]
Has this advanced?

**Comment by KrauseFx** [comment]
Sorry everyone, I didn't find the time to work on this. It seems like a big addition to `deliver`

**Comment by ziadtamim** [comment]
Any update about this feature?

**Comment by KrauseFx** [comment]
@ziadtamim Nothing planned right now

**Comment by facundomedica** [comment]
State of this? Thanks!

**Comment by KrauseFx** [comment]
@facundomedica Nothing planned right now

**Comment by none2011** [comment]
Great job! 
and +1

**Comment by wade0317** [comment]
It would be extremely useful to add/update In-App Purchase, Oh ......

**Comment by elango** [comment]
+1

**Comment by lisbakke** [comment]
+1 one big problem with all of the ASO tools out there (sensor tower, app annie, etc.) is that you can't see when you made IAP price changes.

It would be great if we could manage our IAP via `deliver` because then we'd have a git history of all price changes.
