### ISSUE TITLE
Deliver missing features 1.0.0 beta3

### ISSUE THREAD

**Issue by The-Guru** [fastlane/deliver#350]
Hi Felix,

Some missing features that would be fantastic that the new deliver could have:

+ Avoid uploading screenshots that are the same as the screenshots which are already in iTunes Connect.
+ Support more languages: Traditional Chinese, Canadian French, Indonesian, Malayan, Brazilian Portuguese, Thai, Turkish, Vietnamese.

Thanks.
Best,

Óscar

**Comment by KrauseFx** [comment]
Hey Oscar, 

> Avoid uploading screenshots that are the same as the screenshots which are already in iTunes Connect.
I don't know if and how that's possible yet. I first have to focus to get the first version out and then optimize things.

> Support more languages: Traditional Chinese, Canadian French, Indonesian, Malayan, Brazilian Portuguese, Thai, Turkish, Vietnamese.
These languages should be supported. Do you have troubles uploading them? I think I just don't have the language codes in `Reference.md`

**Comment by sarthak03** [comment]
@KrauseFx Another missing feature is the `version_whats_new.txt` from Metadata. I can't seem to define it inside `Deliverfile`, neither Deliver picks it up from the metadata folder when I add  `version_whats_new.txt` in it.

**Comment by KrauseFx** [comment]
@sarthak03 It's not `version_whats_new.txt`, but `release_notes.txt` instead :+1:

**Comment by KrauseFx** [comment]
I just pushed [deliver 1.0.0](https://github.com/KrauseFx/deliver/releases/tag/1.0.0) and [fastlane 1.30.0](https://github.com/KrauseFx/fastlane/releases/tag/1.30.0). Please update using `sudo gem update fastlane` and let me know if everything works for you.
Also, make sure to follow the new [Migration Guide to 1.0](https://github.com/KrauseFx/deliver/blob/master/MigrationGuide.md).

This issue should be resolved now :+1:
