### ISSUE TITLE
Multiplayer compatibility appears in Korean - deliver 1.1.0

### ISSUE THREAD

**Issue by The-Guru** [fastlane/deliver#362]
@KrauseFx After submitting metadata in several languages (18) it seems that deliver is doing something wrong with Game Center. I have attached a screenshot showing the issue I have.
What do you think?

Thanks.
Best,

Óscar

![app_name_in_korean](https://cloud.githubusercontent.com/assets/3891310/10190784/55889a24-676f-11e5-8e83-f79dcdad31ef.png)

**Comment by KrauseFx** [comment]
Sorry I have to ask: what's wrong? Your app is not Chinese, and suddenly it's Chinese? You support Chinese, but it's not your main language?

**Comment by The-Guru** [comment]
Support Chinese but it's not the main language! Also has happened with French as well

**Comment by KrauseFx** [comment]
`deliver` shouldn't touch GameCenter, I don't know what happened there...

**Comment by KrauseFx** [comment]
Are you sure this happened because of `deliver`? Did this happen for other apps as well?

**Comment by The-Guru** [comment]
What I'm doing right now it's just uploading metadata and screenshots language per language. And I can't tell you when the Game Center multiplayer compatibility is changed but I only using deliver so maybe is some iTunes connect issue ?
