### ISSUE TITLE
In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels , at least 72 DPI, and in the RGB color space - deliver 1.1.0

### ISSUE THREAD

**Issue by The-Guru** [fastlane/deliver#364]
Hi @KrauseFx 

Sometimes I get this error while saving screenshots: 

/Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels, at least 72 DPI, and in the RGB color space. There is an error for 1 of your localizations. (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/tunes_client.rb:275:in `update_app_version!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.1/lib/spaceship/tunes/app_version.rb:265:in `save!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/upload_screenshots.rb:43:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/runner.rb:52:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/runner.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/commands_generator.rb:84:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.1.0/bin/deliver:5:in `<top (required)>'
	from /usr/bin/deliver:23:in `load'
	from /usr/bin/deliver:23:in `<main>'

I have checked that everything in the screenshots is ok (dimensions, 72dpi, rgb color space) but it only appears sometimes. It usually works. What could be happen?

Thanks.
Best

Óscar

**Comment by martynovskij** [comment]
+1
I get the same error.

**Comment by dral3x** [comment]
:+1: here.
Without changing nothing but just re-run the script, the issue goes away.
Of course, screenshots have the correct size, format and dpi.

**Comment by martynovskij** [comment]
re-run the script doesnt work :(

**Comment by dral3x** [comment]
My bad, I meat "sometimes if you re-run script, it works" :)

**Comment by The-Guru** [comment]
Hi Felix,

This is a really important issue...
Because it breaks the screenshots uploads and it's a random issue! sometimes you get the error sometimes not! Any clue about how to resolve it?

**Comment by ericertl** [comment]
I read some comment that re-running makes this issue dissapear, but I run it 4 times and I still get the error. The screenshots where created with snapshot

**Comment by KrauseFx** [comment]
Before I invest a lot of time working into this issue, let's wait for a comment from @lacostej. Also, if any of you has an idea on how to fix this issue, please let me know :+1:

**Comment by PeterCen** [comment]
After comparing some requests from the iTC web interface and from the spaceship client, the error seems occur when one or more of the screenshots doesn't upload properly, but the spaceship client thinks it is uploaded correctly, setting the AssetToken to null.

The ```parse_upload_response``` in ```du_client.rb``` for ```spaceship``` currently checks for ```response.body["statusCode"]``` to be 200 before passing it back ```upload_screenshot``` in ```app_version.rb```, but this field isn't in the response body, checking for the response.status does give '201' for success and '500' for the server error. The ideal solution is that ```du_client``` retries upon receiving a 500 a few times instead of failing on a 500, I'll try to give it a shot (ruby noobie here). Currently, I just added ```return if screenshot_data["token"] == nil``` in line 346 of ```app_version.rb``` to skip adding the screenshot if the token is nil.

Hope this helps, @KrauseFX and thanks for all the great work you've put in :smile:

**Comment by PeterCen** [comment]
Also to make the request consistent with the one made on the iTC web interface, I changed 346 in app_version.rb to ``` new_screenshot = {
              "value" => {
                  "assetToken" => screenshot_data["token"],
                  "sortOrder" => sort_order,
                  #{}"url" => nil,
                  #{}"thumbNailUrl" => nil,
                  "originalFileName" => upload_file.file_name
              },
              "isEditable" => true,
              "isRequired" => false,
              "errorKeys" => nil
          }```

**Comment by pedro380085** [comment]
+1

**Comment by lacostej** [comment]
@PeterCen yup the 201 status is what ITC gives us. 

could you please make a pull request with your changes ?

@KrauseFx  WRT to fail strategy what do you prefer ?

1. du client implements retry (e.g. up to 3 times, with a predefined delay of a few seconds)
2. upload_screenshot fails if du_client doesn

**Comment by lacostej** [comment]
@PeterCen forget about my 'pull request' request.

**Comment by sarthak03** [comment]
Having the same issue. Any fix for this?

**Comment by lacostej** [comment]
@sarthak03 gives us a bit of time :) 

Does someone know what the server returns in the response headers/body if there's a 500 error ? Any log appreciated.

**Comment by sarthak03** [comment]
@lacostej Haha take your time. :)

Also I was wondering if there is an option to skip screenshots only and upload rest of the metadata (icon, descriptione etc.)

**Comment by lacostej** [comment]
@sarthak03 remove your screenshots from your local dir should work I presume ?!

**Comment by PeterCen** [comment]
@lacostej 

HTTP Response Code: 500
```
"<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\"/>\n<title>Error 500 Server Error</title>\n</head>\n<body><h1>500: Server Error</h1>\n</body>\n</html>\n"
```

**Comment by lacostej** [comment]
@PeterCen  that's coming from the du-itc server ? Isn't it only supposed to return json ?

**Comment by PeterCen** [comment]
@lacostej Yep, I got the same response body by logging the response in both the spaceship du client request as well as the POST call made by the iTC Web Interface angular script

**Comment by PeterCen** [comment]
@lacostej I got the status code by calling ```puts response.status``` in ```parse_upload_response``` in ```du_client.rb```.

**Comment by lacostej** [comment]
OK. Then Apple hasn't implemented their 500 response for programmable clients  on the du-itc :) I should have a look again at their ITC javascript client. I wonder if it's doing some retry in there. It's strange that we are the only one facing this. Thanks for the info @PeterCen, I'll try to look into this either tonight or during the week-end.

**Comment by KrauseFx** [comment]
Thank you so much for researching @PeterCen.
@lacostej Retrying up to 5 times would be a great way to solve it from our side. Did you already start working on it?

**Comment by lacostej** [comment]
Made some investigations but not completed. Saw that Faraday has some internal retry mechanism that we could just configure. Or modify the client to accept a custom with_retry. Cannot do more until week end.

**Comment by PeterCen** [comment]
For those who want a temporary fix, I just added 
```
if r.status == 500
        return upload_file(app_version, upload_file, path, content_provider_id, sso_token, du_validation_rule_set)
      end
```
on line 68 of du_client, it just retries the upload if the status return is 500 until it works

**Comment by ericertl** [comment]
@KrauseFx @lacostej , can we have @PeterCen temporary fix implemented in a beta until this gets figured out?

**Comment by PeterCen** [comment]
The full fix should also fix Faraday hard crashing the application when it's connection gets reset (which sometimes happen concurrently with a 500), currently it crashes on this line.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:319:in `syswrite': Broken pipe (Errno::EPIPE)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:319:in `do_write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:337:in `write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:211:in `write0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:185:in `block in write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:202:in `writing'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:184:in `write'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:184:in `send_request_with_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:130:in `exec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1404:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:39:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.10.2/lib/spaceship/client.rb:232:in `block in send_request'
```

**Comment by KrauseFx** [comment]
I can push a temporary fix with the information from @PeterCen

**Comment by The-Guru** [comment]
@KrauseFx @lacostej , can we have @PeterCen temporary fix implemented in a beta until this gets figured out? +1

**Comment by The-Guru** [comment]
@KrauseFx thanks! Sorry for the spam :)

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/spaceship/releases/tag/0.10.3 :rocket:

**Comment by The-Guru** [comment]
@KrauseFx Updating to latest spaceship seems to work in order to upload the screenshots but now I'm facing this error when "saving changes" appears on the console:

/Library/Ruby/Gems/2.0.0/gems/spaceship-0.11.1/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Unauthorized access (Spaceship::TunesClient::ITunesConnectError)

Even when this error appears on the console the screenshots have been saved on iTunes Connect! have you misunderstood the message from the iTunes Connect API?

Thanks.
Best,

Óscar

**Comment by KrauseFx** [comment]
It seems like Apple is currently having timeout issues with iTunes Connect - this isn't an error of `pilot`

**Comment by KrauseFx** [comment]
It seems like Apple is currently having timeout issues with iTunes Connect - this isn't an error of `deliver`. I'll investigate further.

**Comment by none2011** [comment]
Hi @KrauseFx, the same "Unauthorized access" error repeat every time.

**Comment by KrauseFx** [comment]
@none2011 Yes, also see https://github.com/KrauseFx/deliver/issues/349#issuecomment-146333231

**Comment by lacostej** [comment]
For the reference, I got that one a few times today for the first time, then it vanished. Strangely, it was on a project with few screenshots (7 languages, 1 screenshot per device_type), and always failing when saving the last language.

**Comment by artuan** [comment]
Any news on this?

I have an app with 20 languages and I've tried 10 times to upload the screenshots without success.. :/
Can I skip the languages that were already uploaded ?

Thank you!

**Comment by lacostej** [comment]
@artuan we are working on submitting a feature to skip languages that are already submitted. Hopefully submitting it during the week-end for extensive testing. Let me know if you want to try it.

**Comment by artuan** [comment]
@lacostej 
I would love to try! TNX!

**Comment by lacostej** [comment]
@artuan  BTW, I moved the conversation to fastlane/fastlane#1590. This issue is closed.
