### ISSUE TITLE
Deliver init (with version)

### ISSUE THREAD

**Issue by arsonik** [fastlane/deliver#366]
Hello !
First thank you for your amazing work !!!

I wonder if you can implement a way to init with "deliver init -z 3.0" for example.
So deliver can fetch the metadata, screenshots... concerning that specific version and not the last.
I looked around in help/man git issues, don't think that exists !

Cause yes I f**ked up : I init the deliver file with one app and push to another (fastlane) with the info from the first one .... If Apple had the option do delete a version that' d be nice. But they dont't.

So i'm kinda stuck.
Thanks for your help !

**Comment by KrauseFx** [comment]
Oh, sorry to hear you pushed the changes to the wrong app. I'll take a look into this issue
