### ISSUE TITLE
Deliver randomly behaving if ipa contains original Info.plist from Xcode

### ISSUE THREAD

**Issue by Koani** [fastlane/deliver#377]
This issue occurs if you have accidentally compiled your original xcode Info.plist into the binary package, assuming the plist contains user variables for version name (${VERSION_NAME}) and code (${VERSION_CODE}).
In my case Deliver then came up with a random version number which never existed for that target and tried to upload that "version". But the critical part is the following: Instead of the correct bundle identifier it chose the very first app I released in iTunesConnect and tried to modify that one!
(I did not set app, app_identifier or app_version inside Deliverfile.)

In my opinion you should add a notice if multiple Info.plist files are inside the package, to avoid that random behaviour which could really f*ck up your other apps in iTunesConnect.

Thank you
~Koani

**Comment by KrauseFx** [comment]
> In my opinion you should add a notice if multiple Info.plist files are inside the package, to avoid that random behaviour which could really f*ck up your other apps in iTunesConnect.

How can this affect other apps? The bundle identifier is specified in your `Appfile` or `Deliverfile`, right? The only thing that could happen is that the version number on iTunes Connect is set wrong.

You can always pass the version number yourself using the `app_version` option.

**Comment by Koani** [comment]
I do not know, but I can reproduce it. I have a setup with many targets and it *definitely* modified the wrong application in ITC and chose a version number I have never used in this target.
I do not specify any bundle identifier or app version in Deliverfile since I want Deliver to read both from the IPA - which works like a charm when the target checkmark is removed from the Info.plist in xcode.
