### ISSUE TITLE
Sent for review not working

### ISSUE THREAD

**Issue by meyskens** [fastlane/deliver#383]
```
[21:57:41]: [SHELL]: [21:57:34]: Successfully selected build
[21:57:41]: [SHELL]: [21:57:34]: Submitting the app for review...
[21:57:41]: [SHELL]: [21:57:39]: Setting 'content_rights_contains_third_party_content' to 'true'...
[21:57:41]: [SHELL]: [21:57:39]: Setting 'content_rights_has_rights' to 'true'...
[21:57:41]: [SHELL]: [21:57:41]: Successfully submitted the app for review!
```
I get that in my logs but after logging in to iTC I still have to sent it for review manually. Has it anything to do with the content_rights maybe?

**Comment by PeterCen** [comment]
I submitted a pull request https://github.com/fastlane/spaceship/pull/114 and referenced the changes you need to make in your DeliverFile in #360

**Comment by pedro380085** [comment]
@meyskens This same error happens to me too.

**Comment by OlofT** [comment]
I get a similar error:

INFO [2016-03-03 11:47:47.25]: Finished the upload to iTunes Connect
INFO [2016-03-03 11:47:48.01]: Selecting the latest build...
INFO [2016-03-03 11:47:49.21]: Selecting build 1.3 (2)...
INFO [2016-03-03 11:47:49.97]: Successfully selected build
INFO [2016-03-03 11:47:49.97]: Submitting the app for review...
INFO [2016-03-03 11:47:55.33]: Successfully submitted the app for review!

Here it seems to just skip the app_rating_config file - and just claim to be successful...

**Comment by vpolouchkine** [comment]
@OlofT Please share your full setup. Thanks!
