### ISSUE TITLE
Copyright failing

### ISSUE THREAD

**Issue by thekeshavgoel** [fastlane/deliver#386]
Not specific to latest release, bu ever since initial release, if I pass ".....©....." in my copyright text in Deliverfile, The gem fails.
How to pass this hurdle?

**Comment by KrauseFx** [comment]
Sorry, I need more information. Could you post your `Deliverfile` and the complete log when running `deliver`?

**Comment by thekeshavgoel** [comment]
you can try by having you Deliverfile contain this: 

copyright '© 2015'

or 

copyright "© 2015"

probably the string isn't handled aptly, and it is parsing the value, thats why it fails.
For log, I can't share it being in an organisation. You can try for your own, same error shal appear.

**Comment by KrauseFx** [comment]
Maybe there was a new line after the copyright? The next version will automatically trim white spaces.
