### ISSUE TITLE
Anyway to upload any select metadata with an ipa?

### ISSUE THREAD

**Issue by thekeshavgoel** [fastlane/deliver#387]
Though the --skip_metadata is soooo useful!

**Comment by KrauseFx** [comment]
Sorry, I don't understand the question, what do you mean?

**Comment by thekeshavgoel** [comment]
I meant, if for an app update, I want to just add release_notes along with ipa and leaving rest as was previously on iTunes. Is this possible by just providing the ipa [PATH] and release_notes [NOTES] in deliver file?? Or do we need to provide with all the metadat again just to add release_notes..

**Comment by KrauseFx** [comment]
Sorry, that's not possible right now.

**Comment by owurman** [comment]
Is this still not possible? It would be very useful to have a quick way to just create an update with release notes and a new .ipa with no other changes as this is a common use case.

As a workaround I'm just going to use
system('deliver download_metadata')

Then specify a separate release_notes.

By the way, it's not clear from the documentation whether the value of release_notes the actual text, or a path to a text file. I'll figure it out by trial and error.

**Comment by owurman** [comment]
I actually can't figure out how to use release_notes in the Fastfile. I tried this:

`    notes = {"en-us" => "Test Release Notes"}
    deliver(force: false, skip_screenshots: true, skip_binary_upload: true, release_notes: notes)`

But I get the following error:
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] There are one or more errors on the page. (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:347:in `update_app_version!'

**Comment by owurman** [comment]
I was able to reproduce this error regardless of how I passed release notes (Deliverfile, Fastfile, release_notes.txt) so I've filed https://github.com/fastlane/deliver/issues/583
