### ISSUE TITLE
Can deliver upload only screenshots?

### ISSUE THREAD

**Issue by larryonoff** [fastlane/deliver#391]

**Comment by KrauseFx** [comment]
By not providing metadata and binaries, it should only upload screenshots.

**Comment by larryonoff** [comment]
I have Deliver file configured already, with all app store information. Is there any way to disable configuration from Deliverfile?

**Comment by KrauseFx** [comment]
Not easily I guess... sorry, but the option to only upload screenshots isn't available. Why don't you just `deliver init` to download the latest metadata?

**Comment by larryonoff** [comment]
Thats a good idea! Thanks!

**Comment by KrauseFx** [comment]
Sure :+1:
