### ISSUE TITLE
Duplicate App Name unlikely error: "The App Name you entered has already been used."

### ISSUE THREAD

**Issue by RocketPop** [fastlane/deliver#408]
I'm getting this error after updating this afternoon. This is for a completely new app, where produce created the store entries without a problem ("KimiaPMusic" is our app name).
I'm pretty sure that's never been used :) And the iTunes connect web site lets me set this name just fine. I tested the portal site by setting this name to the same name as one of our existing games and it correctly rejects the duplicate name. I modified my Deliver/App meta data to "Kimia P Music" and I get the same error.

``` Ruby
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.11.2/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': The App Name you entered has already been used. The App Name you entered has already been used. (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.11.2/lib/spaceship/tunes/tunes_client.rb:180:in `update_app_details!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.11.2/lib/spaceship/tunes/app_details.rb:65:in `save!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/upload_metadata.rb:58:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/runner.rb:52:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.3.0/lib/deliver/runner.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:137:in `method_missing'
	from (eval):68:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:136:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:142:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

**Comment by none2011** [comment]
same issue occurs.

**Comment by KrauseFx** [comment]
You get the error on iTunes Connect. Someone else probably uses the same name for their iOS App. Can you create a new application on iTunes Connect with that name?

**Comment by RocketPop** [comment]
Hi - actually I don't get the error on iTunes Connect for that name. I can set the name to "KimiaPMusic" just fine. And if I set it to a known duplicate name, iTunes Connect displays an error.
But in a new development, this morning that app entry in iTunes Connect is completely gone (!) i'm on the phone now trying to figure this out. ITC is really broken this last week or so...

**Comment by none2011** [comment]
it happens again here, it seems happen while run the fastlane in 2nd time for an app.
error message shows app name in all language are used, it's weird:

[11:27:14]: The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used.

**Comment by RocketPop** [comment]
It looks like for me, the sigh tool may have failed in some way. Verifying my ipa, the signature was incorrect and I had duplicate certs but one appeared to be invalid. iTunes actually hid that app in the My Apps screen on ITC. I don't know what happened, but I deleted all the certs, provisioning profiles, etc and  I haven't seen this message since. I can't reproduce it either :(

**Comment by KrauseFx** [comment]
https://twitter.com/RaghavMangrola/status/653935880231481344

**Comment by talespring** [comment]
Hi, I'm getting this error now too on an app update.  Should I avoid using certain Fastlane tools  if my app already exists in ITC, and I'm doing an update?  Any ideas on how best to approach this?

Here's my output:
#####################################################
Does the Preview on path './Preview.html' look okay for you? (y/n)
y
[00:10:22]: HTML file confirmed...
[00:10:24]: Activating language en-US...
[00:10:26]: Uploading metadata to iTunes Connect
[00:10:27]: Variable Dump:
[00:10:27]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios appstore", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/Output-TS-ipa/HowtoPray-1.10.ipa", :DSYM_OUTPUT_PATH=>"/Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/Output-TS-ipa/HowtoPray-1.10.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/tsdev/Library/Developer/Xcode/Archives/2016-02-23/HowtoPray-1.10 2016-02-23 23.59.58.xcarchive", :PRODUCE_APPLE_ID=>"587992254"}
[00:10:27]: The App Name you entered has already been used. The App Name you entered has already been used.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | match                               | 5           |
| 4    | gym                                 | 14          |
| 5    | produce                             | 4           |
| 6    | deliver                             | 611         |
+------+-------------------------------------+-------------+

[00:10:27]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] The App Name you entered has already been used. The App Name you entered has already been used. (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:240:in `update_app_details!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/app_details.rb:69:in `save!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/upload_metadata.rb:60:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:58:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:60:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.7/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
#######################################

**Comment by dpettit** [comment]
FYI, the above link is dead at this point.

I'm experiencing the same issue when use Fastlane to update an existing app in the app store.  Should I be leaving some Fastlane actions out of my Fastfile if I'm resubmitting an update to an existing app?

Here is my output:

########################################
Does the Preview on path './Preview.html' look okay for you? (y/n)
y
[00:10:22]: HTML file confirmed...
[00:10:24]: Activating language en-US...
[00:10:26]: Uploading metadata to iTunes Connect
[00:10:27]: Variable Dump:
[00:10:27]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios appstore", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/Output-TS-ipa/HowtoPray-1.10.ipa", :DSYM_OUTPUT_PATH=>"/Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/Output-TS-ipa/HowtoPray-1.10.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/tsdev/Library/Developer/Xcode/Archives/2016-02-23/HowtoPray-1.10 2016-02-23 23.59.58.xcarchive", :PRODUCE_APPLE_ID=>"587992254"}
[00:10:27]: The App Name you entered has already been used. The App Name you entered has already been used.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | match                               | 5           |
| 4    | gym                                 | 14          |
| 5    | produce                             | 4           |
| 6    | deliver                             | 611         |
+------+-------------------------------------+-------------+

[00:10:27]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] The App Name you entered has already been used. The App Name you entered has already been used. (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:240:in `update_app_details!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/app_details.rb:69:in `save!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/upload_metadata.rb:60:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:58:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:60:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.7/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
########################################
