### ISSUE TITLE
Error "Unauthorized access" when saving meta data

### ISSUE THREAD

**Issue by plaetzchen** [fastlane/deliver#412]
Hi,

I get the error "Unauthorized access" when deliver tries to save uploaded screenshots in iTunes connect. Login works and I can save thinks manually. Anyway to fix this?

Bests,
Philip.

**Comment by SPAHI4** [comment]
same error when releasing app

**Comment by none2011** [comment]
yes, see #349 (comment)

**Comment by plaetzchen** [comment]
Which comment do you mean? I can't find a solution in there.

**Comment by cdemiris99** [comment]
I'm seeing the "Unauthorized Access" when it's doing the "Saving Changes" after all screenshots are uploaded (for me the metadata uploads fine and changes in itc).

**Comment by plaetzchen** [comment]
Oh yeah it does upload and save but I get an exception and the IPA is not uploaded and all other steps are not executed (of course)
