### ISSUE TITLE
price_tier setting not works in deliver file

### ISSUE THREAD

**Issue by none2011** [fastlane/deliver#413]
First, thank you so much for the great job!

it seems the original way of setting price tier in the deliver file does not works, although there is no error message during uploading.

I set this in the deliverfile as before, but it isn't set in ITC after all.
price_tier 2

**Comment by KrauseFx** [comment]
I have the feeling that somehow `deliver` doesn't edit the right app on iTunes Connect. Do you have multiple apps? Are you sure you're editing the correct app? All your issues are like `I want to change X, it succeeds, but it doesn't appear online`

**Comment by none2011** [comment]
yes, i have multiple apps. here is the log, it did show that price_tier has error.

It has right summary: but, fail in the end, either price_tier, nor app_icon were uploaded.

+------------------------+---------------------------------+
|                         Summary                          |
+------------------------+---------------------------------+
| username               | ****@gmail.com         |
| app_identifier         | com.****.qzdragonage       |
| ipa                    | Quiz for Dragon Age.ipa         |
| metadata_path          | ./fastlane/metadata             |
| screenshots_path       | ./fastlane/./screenshots        |
| skip_screenshots       | false                           |
| app_version            | 1.0                             |
| skip_metadata          | false                           |
| force                  | false                           |
| submit_for_review      | false                           |
| automatic_release      | true                            |
| price_tier             | 3                               |
| app_rating_config_path | ./fastlane/rating_config17.json |
| app_icon               | ./fastlane/appicon1024.png      |
| app_review_information |                                 |
+------------------------+---------------------------------+


HTML file confirmed...
[11:50:58]: Activating languages de-DE, en-US, es-ES, es-MX, fr-FR, ja, ko, pt-BR, pt-PT, ru, zh-Hans...
[11:51:01]: Uploading metadata to iTunes Connect
[11:51:06]: Successfully uploaded initial set of metadata to iTunes Connect
[11:51:07]: Starting with the upload of screenshots...
[11:51:07]: Uploading './fastlane/./screenshots/de-DE/en-US-iPad-0-LandingScreen1-portrait_framed.png'...
[11:51:09]: Uploading './fastlane/./screenshots/de-DE/en-US-iPad-0-LandingScreen2-portrait_framed.png'...
[11:51:11]: Uploading './fastlane/./screenshots/de-DE/en-US-iPad-0-LandingScreen3-portrait_framed.png'...
.......
[12:00:18]: Uploading './fastlane/./screenshots/zh-Hans/en-US-iPhone6Plus-0-LandingScreen5-portrait_framed.png'...
[12:00:20]: Saving changes
[12:00:21]: Variable Dump:
[12:00:21]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios d", :SIGH_PROFILE_PATH=>"/Volumes/Macintosh HD 2/_AppBiz/AppProjects/Dropbox/QZ_Temp/QZ_A_43-69/43.Dragon Age_NR/AppStore_com.****.qzdragonage.mobileprovision", :SIGH_PROFILE_PATHS=>["/Volumes/Macintosh HD 2/_AppBiz/AppProjects/Dropbox/QZ_Temp/QZ_A_43-69/43.Dragon Age_NR/AppStore_com.*****.qzdragonage.mobileprovision"], :SIGH_UDID=>"f465334e-3e45-42e8-a115-deb2e2690f62", :SIGH_PROFILE_TYPE=>"app-store"}
[12:00:21]: Failed to create an app icon Failed to create an app icon

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | sigh                                | 5           |
| 4    | deliver                             | 595         |
+------+-------------------------------------+-------------+

[12:00:21]: fastlane finished with errors
/Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.12.0/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Failed to create an app icon Failed to create an app icon (Spaceship::TunesClient::ITunesConnectError)
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.12.0/lib/spaceship/tunes/tunes_client.rb:278:in `update_app_version!'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.12.0/lib/spaceship/tunes/app_version.rb:265:in `save!'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.3.2/lib/deliver/upload_screenshots.rb:45:in `upload'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.3.2/lib/deliver/runner.rb:53:in `upload_metadata'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.3.2/lib/deliver/runner.rb:20:in `run'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:127:in `execute_action'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:19:in `block (2 levels) in parsing_binding'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/lane.rb:36:in `call'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/lane.rb:36:in `call'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:51:in `block in execute'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:46:in `execute'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/bin/fastlane:35:in `block (2 levels) in run'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/bin/fastlane:136:in `run'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.32.4/bin/fastlane:142:in `<top (required)>'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/bin/fastlane:23:in `load'
	from /Users/developerZ/.rvm/rubies/ruby-2.2.3/bin/fastlane:23:in `<main>'
	from /Users/developerZ/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/developerZ/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
