### ISSUE TITLE
Could not find app with app identifier '$(PRODUCT_BUNDLE_IDENTIFIER)' in your account

### ISSUE THREAD

**Issue by none2011** [fastlane/deliver#415]
Hi, It seems this error random happens. I'm sure the identifier is set correctly in the xcode and fastfile.

**Comment by KrauseFx** [comment]
`$(PRODUCT_BUNDLE_IDENTIFIER)` is a placeholder for your real app identifier? Or is that the message you get? Can you post the complete log when running `deliver`.

You could also try passing the app identifier manually to `deliver` or declare it in your `Deliverfile`:

```
deliver --help
```

```
    -a, --app_identifier STRING The bundle identifier of your app (DELIVER_APP_IDENTIFIER)
```

**Comment by squarefrog** [comment]
Related to https://github.com/KrauseFx/fastlane/issues/684.
