### ISSUE TITLE
keywords can't include whitespace

### ISSUE THREAD

**Issue by kostiakoval** [fastlane/deliver#418]
keywords.txt file
```
One
Some other
Find my dog
```

The deliver will generate these keywords:
```
- One
- Some
- other
- Find
- my
- dog
```
The solution is to use the Non-breaking space (⌥ Opt+Space)

**Comment by iPavel92** [comment]
The same issue with deliverfile:
```
keywords({
'ru' => "KeywordOne, KeywordTwo, Keyword With Spaces"
})
```
will generate
```
KeywordOne,
KeywordTwo,
Keyword
With
Spaces
```
Also deliver attaches comma to keyword

**Comment by iPavel92** [comment]
By the way, seems like keywords string from the deliverfile passed to iTC as is. So actually everything is OK and this is an issue of html preview only.

**Comment by dral3x** [comment]
`keywords` now requires a simple string with comma separated keywords.
Maybe it's just the preview that list them badly
