### ISSUE TITLE
[Feature Request] Allow app_review_information in metadata file

### ISSUE THREAD

**Issue by klavergne** [fastlane/deliver#426]
Currently the app_review_information is only allowed in the Deliverfile. But in a company like mine where the dev team is different from the deploy team, we need to be able to provide this app_review_information separate from the "deploy script" (Deliverfile), similar to how we provide the screenshots and metadata.

**Comment by KrauseFx** [comment]
Of course, the `Deliverfile` is a standard Rubyfile. You can do something like that:

```ruby
require 'json'

title JSON.parse(File.read("title.json"))
```

This works for all attributes and options.

**Comment by klavergne** [comment]
I tried that, but the `app_review_information` shows as blank and doesn't get uploaded to ITC.

```
+------------------------+---------------------------------+
|                         Summary                          |
+------------------------+---------------------------------+
| username               | myappleid@something.com         |
| app_identifier         | my.appid                        |
| metadata_path          | ./metadata                      |
| screenshots_path       | ./screenshots                   |
| skip_screenshots       | false                           |
| skip_metadata          | false                           |
| force                  | true                            |
| submit_for_review      | false                           |
| automatic_release      | false                           |
| app_review_information |                                 |
+------------------------+---------------------------------+
```

From my `Deliverfile`:
```ruby
require 'json'

app_review_information JSON.parse(File.read("./metadata/app_review_information.json"))
```

From the `app_review_information.json` file:
```json
{
 "first_name": "Kevin",
 "last_name": "LaVergne",
 "phone_number": "+1 883738893",
 "email_address": "someone@somewhere.com",
 "demo_user": "xxx",
 "demo_password": "test123",
 "notes": "some notes"
}
```

**Comment by KrauseFx** [comment]
Interesting, does it work though? Maybe it's just an error in the output?

**Comment by klavergne** [comment]
No, it doesn't update in ITC. If I put it directly in the `Deliverfile` as a hash (not JSON), it does update.

**Comment by lacostej** [comment]
I looked into that. I believe it's because the value passed as a Hash to the Terminal table in fastlane_core isn't properly displayed. We could expand Hashes that way (crude test)

````
          if value.respond_to? :key
            value.each do |k,v|
              rows << ["#{config_item.key}.#{k}", v[0..100]]
            end
          else
            rows << [config_item.key, value]
          end
```
but it requires further filtering (e.g. app_review_information can contains password)

**Comment by lacostej** [comment]
I implemented the backend for it in fastlane_core https://github.com/fastlane/fastlane_core/pull/38 and hide the demo password in deliver in https://github.com/KrauseFx/deliver/pull/439

I am unhappy about one thing, the terminal table we link to is buggy and causes issues if we want to use maximum table length. So the app_review_information displays a bit ugly if the contained review notes for example are on long lines.

**Comment by klavergne** [comment]
I'm sure it would also be a problem for multi-line review notes.

**Comment by lacostej** [comment]
As seen in https://github.com/lacostej/fastlane_core/blob/2b36de7a3c159cc2437a511d874f9ccbd1a3f793/lib/fastlane_core/print_table.rb#L15, we could use the :style option to ensure the length, but it is broken in 1.4.5. And all my attempts at upgrading to a newer terminal-tablet gem have failed.

I sent a patch to shenzhen to relax its dependencies, but we would also have to wait for an update of shenzhen and update our dependency to it. Except if there's a ruby gem that I don't know of.

In the mean time, I can do the original hack, which is to limit the length of a value string to a reasonable amount.

I'll do it right away.

**Comment by lacostej** [comment]
fastlane/fastlane_core#38  updated with an artificial max column length (100)
