### ISSUE TITLE
[Feature Request] Connection error handling and recovery

### ISSUE THREAD

**Issue by facundomedica** [fastlane/deliver#428]
What do you guys think about a connection error handling in deliver? iTunes may fail quite frequently and it's not funny when you been waitin for hours for your build to be processed (happened to me yesterday, 471 minutes and then failed).
As far as I know from what I read in other issues, the following error is caused by a server timeout:
```
{"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Unauthorized access"]}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
```

Is it possible to keep trying after a connection fails? And making something like this?:
```
Connection failed, retrying in 1 minute...
Connection failed, retrying in 2 minutes...
Connection failed, retrying in 4 minutes...
```

**Comment by KrauseFx** [comment]
`spaceship` is actually doing this already:

```ruby
    def with_retry(tries = 5, &block)
      return block.call
    rescue Faraday::Error::TimeoutError => ex # New Faraday version: Faraday::TimeoutError => ex
      unless (tries -= 1).zero?
        sleep 3
        retry
      end

      raise ex # re-raise the exception
    end
```
