### ISSUE TITLE
Can't upload screenshots.

### ISSUE THREAD

**Issue by skywinder** [fastlane/deliver#436]
Hmm.. Got error, when try to upload screenshots by command `deliver --skip_metadata`

```
...
[18:15:06]: Uploading './fastlane/screenshots/zh-Hant/5_iphone6Plus_5.62d7de2e26ca60f529a2656e02e310e9.png'...
[18:15:10]: Saving changes
/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/spaceship-0.12.1/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Unauthorized access (Spaceship::TunesClient::ITunesConnectError)
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/spaceship-0.12.1/lib/spaceship/tunes/tunes_client.rb:278:in `update_app_version!'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/spaceship-0.12.1/lib/spaceship/tunes/app_version.rb:265:in `save!'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/deliver-1.3.2/lib/deliver/upload_screenshots.rb:45:in `upload'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/deliver-1.3.2/lib/deliver/runner.rb:53:in `upload_metadata'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/deliver-1.3.2/lib/deliver/runner.rb:20:in `run'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/deliver-1.3.2/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/deliver-1.3.2/lib/deliver/commands_generator.rb:84:in `run'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/deliver-1.3.2/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/deliver-1.3.2/bin/deliver:5:in `<top (required)>'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/deliver:23:in `load'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/deliver:23:in `<main>'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

Seems problem in `update_app_version`.. But there is not any problems if I just try to run `deliver`.

**Comment by mariecl** [comment]
I also have this error (though I didn't use the `--skip_metadata`), though the screenshots and all metadata did upload properly to iTunes Connect (after a while).

**Comment by skywinder** [comment]
Hey,  @twitter , @crashlytics  welcome to @fastlane! :wink: 
Please, help us! :+1:

**Comment by leonspok** [comment]
Same problem with spaceship-0.12.2

	/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.12.2/lib/spaceship/tunes/tunes_client.rb:147:in `handle_itc_response': Unauthorized access (Spaceship::TunesClient::ITunesConnectError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.12.2/lib/spaceship/tunes/tunes_client.rb:278:in `update_app_version!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.12.2/lib/spaceship/tunes/app_version.rb:265:in `save!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.3.3/lib/deliver/upload_screenshots.rb:45:in `upload'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.3.3/lib/deliver/runner.rb:53:in `upload_metadata'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.3.3/lib/deliver/runner.rb:20:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.3.3/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.3.3/lib/deliver/commands_generator.rb:84:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.3.3/lib/deliver/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.3.3/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'

**Comment by leonspok** [comment]
Problem isn't gone with spaceship 0.13.0.

**Comment by skywinder** [comment]
Please, fix it! Here is reference to you new crash reporting tool: 3613a9a2fd35f2eb9b508aa109b6e008

**Comment by KrauseFx** [comment]
@skywinder Really sorry for the delay, @snatchev has been working on a big upgrade for `spaceship` with https://github.com/fastlane/spaceship/releases/tag/0.15.2, which took a bit longer to test. Could you please update to `0.15.2` using `sudo gem update spaceship` and let us know if that solves the problem?

**Comment by helguita** [comment]
looks like problem is not gone with spaceship 0.19.0 😭
here is a reference to the crash: 54f64c32426ef14747e3cb1c942f13d5

**Comment by skywinder** [comment]
I don't know is it some changes in `spaceship` or not. But in my case problem solved.
