### ISSUE TITLE
Uploading new ipa without affecting display version number

### ISSUE THREAD

**Issue by emablekos** [fastlane/deliver#459]
I have a version uploaded to itunes that is waiting for review: 1.1

I build a new version and uploaded via deliver so i can send it to internal testflight users. The version being uploaded is 1.2

This is being done via bitrise, the following code is used to deliver:
https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver/blob/master/step.sh#L103

Unfortunately this call also changes the metadata "Version" on the PUBLIC (waiting for review) itunes metadata (under "General Information") to 1.2...

Expected result: iTunes public metadata version number remains at 1.1, but the new version is uploaded for me to eventually release 1.2 to internal testflight.

Is there a way to achieve this?

**Comment by jaleksynas** [comment]
I consider the updated version number when 'in review' to be a bug. See #478.  

Also pertaining to the Apple limitation of having only one non-live version at a time: http://stackoverflow.com/questions/22156933/can-i-submit-multiple-versions-of-the-same-app-to-the-apple-store
