### ISSUE TITLE
problem updating screenshots

### ISSUE THREAD

**Issue by fmessier** [fastlane/deliver#461]
Hello,

I have an error every time i'm trying to upload screenshots using deliver. i tried with version 1.4.0 and 1.5.0. Here is the error in the output of deliver:

[10:54:15]: Starting with the upload of screenshots...
[10:54:15]: Uploading './screenshots/de-DE/TFED_SCREENSHOT_IPAD_DE_1.jpg'...
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/tunes/app_version.rb:496:in `container_data_for_language_and_device': Unexpected state: missing device details for ipad (RuntimeError)
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/tunes/app_version.rb:481:in `screenshots_data_for_language_and_device'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/tunes/app_version.rb:340:in `upload_screenshot!'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.5.0/lib/deliver/upload_screenshots.rb:38:in `block in upload'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.5.0/lib/deliver/upload_screenshots.rb:25:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.5.0/lib/deliver/upload_screenshots.rb:25:in `upload'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.5.0/lib/deliver/runner.rb:53:in `upload_metadata'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.5.0/lib/deliver/runner.rb:20:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.5.0/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.5.0/lib/deliver/commands_generator.rb:111:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.5.0/lib/deliver/commands_generator.rb:12:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.5.0/bin/deliver:5:in `<top (required)>'
    from /usr/bin/deliver:23:in `load'
    from /usr/bin/deliver:23:in `<main>'

Thank you for your support and for writing this invaluable tool :)

**Comment by lacostej** [comment]
the code expect the app_version to contain something lik

```
                    "screenshots": {
                        "value": {
                            "ipad": {
                                "value": [],
                                "isEditable": false,
                                "isRequired": true,
                                "errorKeys": null
                            },
```

It looks like it doesn't.

@fmessier  could you try dumping the appversion JSON details ?

If you know your way in your browser developer tools, you should find a URL like

https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/111111111111/platforms/ios/versions/222222222222

If you can't find it, we can help you download it.

**Comment by eschweichler** [comment]
This is the response that we are receiving:

I tried and it is the same for all our apps as far as I can tell.

{"data":null,"messages":{"warn":null,"info":null,"error":["Invalid versionId"]},"statusCode":"ERROR"}

Here's an example from my personal iTC account, same error for this url:

https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/369881803/platforms/ios/versions/5.0

**Comment by lacostej** [comment]
@eschweichler I doubt versionId in the URL should be 5.0

**Comment by fmessier** [comment]
Hello,

Ok what can I do to get an actual versionId for one of my apps?

Thanks.

**Comment by fmessier** [comment]
OK i was able to find a versionid. The json file returned is pretty big but for each language there is this info somewhere : 

"screenshots":{"value":{"ipadPro":{"value":[],"isEditable":true,"isRequired":false,"errorKeys":null},"watch":{"value":[],"isEditable":true,"isRequired":false,"errorKeys":null},"iphone4":{"value":[],"isEditable":true,"isRequired":false,"errorKeys":null},"iphone35":{"value":[],"isEditable":true,"isRequired":false,"errorKeys":null},"iphone6":{"value":[],"isEditable":true,"isRequired":false,"errorKeys":null},"ipad":{"value":[],"isEditable":true,"isRequired":false,"errorKeys":null},"iphone6Plus":{"value":[],"isEditable":true,"isRequired":false,"errorKeys":null}},"isEditable":true,"isRequired":false,"errorKeys":null}

**Comment by bwang29** [comment]
I'm having similar issues with /Library/Ruby/Gems/2.0.0/gems/spaceship-0.18.1/lib/spaceship/tunes/app_version.rb:496:in `container_data_for_language_and_device': Unexpected state: missing device details for mac (RuntimeError)

the response is {"value"=>{"desktop"=>{"value"=>[{"value"=>{"assetToken"=>"Purple69/v4/ee/1c/d3/ee1cd33d-ec59-b718-714b-1359bf3c7395/pr_source.png", "sortOrder"=>1, "originalFileName"=>"de_2880x1800_powerful_tools.png"}, "isEditable"=>true, "isRequired"=>false, "errorKeys"=>nil}, {"value"=>{"assetToken"=>"Purple69/v4/d9/41/9e/d9419e43-5fd1-143b-2a2a-eec8b8c32894/pr_source.png", "sortOrder"=>2, "originalFileName"=>"de_2880x1800_customize.png"}, "isEditable"=>true, "isRequired"=>false, "errorKeys"=>nil}, {"value"=>{"assetToken"=>"Purple69/v4/3b/84/b3/3b84b3ca-c61d-ddcf-978e-21e81359ce12/pr_source.png", "sortOrder"=>3, "originalFileName"=>"de_2880x1800_local_adjustments.png"}, "isEditable"=>true, "isRequired"=>false, "errorKeys"=>nil}, {"value"=>{"assetToken"=>"Purple69/v4/25/26/81/2526810c-6a1d-b086-87e4-1f4f908b58ab/pr_source.png", "sortOrder"=>4, "originalFileName"=>"de_2880x1800_history.png"}, "isEditable"=>true, "isRequired"=>false, "errorKeys"=>nil}, {"value"=>{"assetToken"=>"Purple69/v4/1a/76/76/1a767685-5b42-2825-da7a-7393d7ccddff/pr_source.png", "sortOrder"=>5, "originalFileName"=>"de_2880x1800_preset_styles.png"}, "isEditable"=>true, "isRequired"=>false, "errorKeys"=>nil}], "isEditable"=>true, "isRequired"=>false, "errorKeys"=>nil}}, "isEditable"=>true, "isRequired"=>false, "errorKeys"=>nil}
