### ISSUE TITLE
can't update app in itunes

### ISSUE THREAD

**Issue by romk1n** [fastlane/deliver#469]
when running `deliver -z 3.0.0` I am getting this error when trying to update screenshots and metadata of the app 

```
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.13.0/lib/spaceship/tunes/tunes_client.rb:148:in `handle_itc_response': You cannot create a new version of the App in the current state. (Spaceship::TunesClient::ITunesConnectError)
```
version:
`deliver 1.5.0`

**Comment by KrauseFx** [comment]
I can only assume that the app is currently in review or similar. Do you still run into this issue?
