### ISSUE TITLE
Is it possible to use deliver to upload xcarchive files to the app store?

### ISSUE THREAD

**Issue by Apocryphon** [fastlane/deliver#473]
Current workflow is to click on the *.xcarchive file in Finder, then Upload to App Store... via the Organizer window in Xcode.

Is there a similar way for Deliver to submit xcarchive files?

**Comment by martinpucik** [comment]
You can use [gym](https://github.com/fastlane/gym) to build .ipa and then `deliver` to upload it to AppStore.

**Comment by Apocryphon** [comment]
I understand, but can `deliver` upload xcarchive files?

**Comment by martinpucik** [comment]
AFAIK You don't need to upload xcarchive files anywhere. You build your project with `gym` and upload the .ipa with `deliver` 😎

**Comment by JonB** [comment]
@Apocryphon the Organizer window in Xcode creates an IPA then uploads that to iTunes connect

**Comment by lacostej** [comment]
@Apocryphon if you want to use deliver to upload, and do not want to change your workflow to generate the xcarchive, you will need to generate your IPA from your .xcarchive.

Multiple ways:
* I don't think gym can do it yet for you directly (see fastlane/gym#12) but maybe [fastlane xcexport](https://github.com/fastlane/fastlane/blob/master/docs/Actions.md#user-content-xcodebuild) can
* a script (see [gym documentation](https://github.com/fastlane/gym/#user-content-xcode-7-and-above))
