### ISSUE TITLE
fastlane finished with errors "This train could not be activated because the build(s) is not set expiration date properly"

### ISSUE THREAD

**Issue by mdeandreis** [fastlane/deliver#485]
I´am running fastlane beta to upload a new ios app version. The app is uploaded to Testflight, but fastlane finished with errors. I don´t have idea what could it be, any idea?

Yesterday, I updated fastlane to the latest version
 
In the crash report, I can see:
"Spaceship::TunesClient::ITunesConnectError: This train could not be activated because the build(s) is not set expiration date properly."

Thanks,
Martin

**Comment by tabuchid** [comment]
I'm also seeing this.

**Comment by mdeandreis** [comment]
Now I´m having this issue:
"message": "Spaceship::Tunes Client::ITunes Connect Error: This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved. This build could not be used for external testing because the build is not approved.",

The app is available in Itunes Connect and I have installed the app and works fine
Thanks,
Martin

**Comment by KrauseFx** [comment]
Interesting, same issue over there https://github.com/fastlane/spaceship/issues/175
