### ISSUE TITLE
Deliver does not use the file produced from gym when using fastlane

### ISSUE THREAD

**Issue by plaetzchen** [fastlane/deliver#486]
Hi,

I run gym using fastlane and deliver seems to fail to find the correct IPA file. It uploads an old version with an old version. Is there a way to fix this?

Bests,
Philip

**Comment by KrauseFx** [comment]
Can you share your `Fastfile` and `Deliverfile`?

**Comment by Dahlgren** [comment]
I'd guess the reason is https://github.com/fastlane/deliver/blob/master/lib/deliver/options.rb#L32

Can be fixed in your `Fastlane` file by passing `lane_context[SharedValues::IPA_OUTPUT_PATH]` to the `ipa` option of the `deliver` step
