### ISSUE TITLE
Updating metadata

### ISSUE THREAD

**Issue by tylerweitzman** [fastlane/deliver#493]
Hi,
I would like to use deliver to update an existing version that is already Ready For Sale. In particular, I would like to be able to update the price tier from the command line. Any help?
Currently I try `deliver run --skip_screenshots -r 3` and get back "The version number has been previously used."

Thanks!

**Comment by tylerweitzman** [comment]
Going to answer my own question here:
Seems deliver does not support updating current version -- reasonable since some fields are inaccessible once the app is ready for sale (e.g Keywords and Screenshots). However, doing what is described above is super simple using spaceship

`app.update_price_tier!("3")`

**Comment by KrauseFx** [comment]
```
deliver --help | grep "version"
```
```
    -z, --app_version STRING The version that should be edited or created
```

Does that help? You can specify the version to be edited.
