### ISSUE TITLE
deliver/submit says it worked - but doesn't

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/deliver#496]
fastlane says it has done everything correctly, and does select the correct build, but iTunes connect still shows ‘prepare for submission’

any ideas?

my lane:

	  desc "Submit for review"
	  lane :submit do
	  
	    deliver(
	      force: true, #don't review upload; we're not uploading anything
	      skip_screenshots: true,
	      skip_metadata: true,
	      submit_for_review: true)
	
	  end

my deliver file

	submission_information({
	  add_id_info_uses_idfa: ENV['DLV_SERVES_ADS'],
	  export_compliance_uses_encryption: false
	})

the output:

	[20:03:01]: -------------------------------------------------
	[20:03:01]: --- Step: Verifying required fastlane version ---
	[20:03:01]: -------------------------------------------------
	[20:03:01]: fastlane version valid
	[20:03:01]: ------------------------------
	[20:03:01]: --- Step: default_platform ---
	[20:03:01]: ------------------------------
	[20:03:01]: Loading from './fastlane/.env.legacy'
	[20:03:01]: Driving the lane 'ios submit' 🚀
	[20:03:01]: ---------------------
	[20:03:01]: --- Step: deliver ---
	[20:03:01]: ---------------------
	[20:03:01]: Login to iTunes Connect (hobbyist@hobbyistsoftware.com)
	[20:03:04]: Login successful
	
	+------------------------+------------------------------------+
	|                    deliver 1.5.1 Summary                    |
	+------------------------+------------------------------------+
	| username               | hobbyist@hobbyistsoftware.com      |
	| app_identifier         | com.HobbyistSoftware.VLCRemoteIPad |
	| metadata_path          | ./fastlane/legacy/metadata/        |
	| screenshots_path       | ./fastlane/legacy/screenshots/     |
	| skip_screenshots       | true                               |
	| skip_metadata          | true                               |
	| force                  | true                               |
	| submit_for_review      | true                               |
	| automatic_release      | false                              |
	| submission_information |                                    |
	| copyright              | 2015 Hobbyist Software Ltd.        |
	| release_notes          |                                    |
	+------------------------+------------------------------------+
	
	[20:03:06]: Detected languages: ["default", "de-DE", "el", "en-US", "es-ES", "fi", "fr-FR", "it", "ja", "nl-NL", "pt-PT", "ru", "sv"]
	[20:03:13]: Finished the upload to iTunes Connect
	[20:03:13]: Selecting the latest build...
	[20:03:19]: Selecting build 9.11 (60)...
	[20:03:21]: Successfully selected build
	[20:03:21]: Submitting the app for review...
	[20:03:30]: Setting 'add_id_info_uses_idfa' to 'false'...
	[20:03:30]: Setting 'export_compliance_uses_encryption' to 'false'...
	[20:03:32]: Successfully submitted the app for review!
	
	+------+-------------------------------------+-------------+
	|                     fastlane summary                     |
	+------+-------------------------------------+-------------+
	| Step | Action                              | Time (in s) |
	+------+-------------------------------------+-------------+
	| 1    | Verifying required fastlane version | 0           |
	| 2    | default_platform                    | 0           |
	| 3    | deliver                             | 30          |
	+------+-------------------------------------+-------------+
	
	[20:03:32]: fastlane.tools finished successfully 🎉

**Comment by pedro380085** [comment]
Same thing is happening here.

**Comment by NikhilRyan** [comment]
+1 Same here.

**Comment by EdwinRikkers** [comment]
+1

**Comment by gran33** [comment]
+1 same here
How can I set ```submission_information``` in command line?
```deliver --submission_information ...```

**Comment by sarthak03** [comment]
Any workaround for this? Which file in the fastlane library triggers this?

**Comment by sunboshan** [comment]
Setting this two value to false should work..

    submission_information({
      add_id_info_uses_idfa: false,
      export_compliance_uses_encryption: false
    })

**Comment by pedro380085** [comment]
@sunboshan Both values are set to off on my Deliverfile.

**Comment by sarthak03** [comment]
Yes even after setting that it doesn't work. It only selects the build and doesn't submit for review.

**Comment by sunboshan** [comment]
Interesting. Since iTunesConnect will close for a week. Will try to figure this out when ITC comes back.

**Comment by HughJeffner** [comment]
Same deal here, I get the following output but status is still "Prepare for Submission"

```
INFO [2016-01-04 14:58:39.80]: Finished the upload to iTunes Connect
INFO [2016-01-04 14:58:39.80]: Selecting the latest build...
INFO [2016-01-04 14:58:42.35]: Selecting build 1.11.0 (279)...
INFO [2016-01-04 14:58:43.08]: Successfully selected build
INFO [2016-01-04 14:58:43.08]: Submitting the app for review...
INFO [2016-01-04 14:58:46.97]: Setting 'add_id_info_uses_idfa' to 'false'...
INFO [2016-01-04 14:58:46.97]: Setting 'export_compliance_uses_encryption' to 'false'...
INFO [2016-01-04 14:58:48.09]: Successfully submitted the app for review!

**Comment by HughJeffner** [comment]
Is there a way to see what Spaceship is doing behind the scenes? I might have to set up a proxy with TLS to examine these requests. From looking at the code it looks like it determines if the submission was successful here:

https://github.com/fastlane/spaceship/blob/27a8d7d8107e6914913dba6eb7933209e0c0e0e0/lib/spaceship/tunes/tunes_client.rb#L678

I am not really a Ruby user so I don't have a dev environment set up to step through and see if it's just ITC acting wacky or the success condition needs an update.

**Comment by HughJeffner** [comment]
Spaceship doesn't appear to be using the system proxy, any way to get it to?

**Comment by HughJeffner** [comment]
After digging through the JSON with Charles I finally figured this out.  If you are adding a new version of an existing app you need `export_compliance_encryption_updated: false` in your submission information.

**Comment by pedro380085** [comment]
@HughJeffner What's the logic behind `export_compliance_encryption_updated: false`? Just a curiosity.

**Comment by pedro380085** [comment]
@HughJeffner You don't declare the other properties? So I can check with my config here.

**Comment by HughJeffner** [comment]
If you manually submit the app through ITC on the submission page you get the export compliance message:

![ec_itc](https://cloud.githubusercontent.com/assets/9453825/12201375/abc69e7c-b5e9-11e5-9883-5d746a093d8f.png)

I think `export_compliance_encryption_updated` controls that setting during the submission, it seems required.  If you select yes to that question then another question appears that I think corresponds to `export_compliance_uses_encryption`.

 Those 3 are the only properties I have set in my Deliverfile

**Comment by HughJeffner** [comment]
Just found #360 and this seems like the same issue.  I think there needs to be *sensible defaults* in place somewhere.  If you don't supply a value it gets set to null in the JSON.

**Comment by ConfusedVorlon** [comment]
I suspect Felix wouldn't want to set a default value that was a declaration you us that we have done something. Which means this is probably one for the documentation.

I believe the wiki pages are open for edits, and I know Felix accepts pull requests for the documentation pages.

**Comment by HughJeffner** [comment]
I was thinking of the generated Deliverfile, or perhaps a warning when trying to submit with certain values not defined.  But yeah, this needs to be in the docs.

**Comment by sunboshan** [comment]
@HughJeffner Yes. For some apps, it needs to set `false` to all these three value to work. Confirmed.

    submission_information({
      add_id_info_uses_idfa: false,
      export_compliance_uses_encryption: false,
      export_compliance_encryption_updated: false
    })

**Comment by programmin1** [comment]
To be clear... is there any command line submission information argument that works with deliver command?

I tried --submission_information "{add_id_info_uses_idfa: false, export_compliance_uses_encryption: false, export_compliance_encryption_updated: false}"
 and it gives an error.

**Comment by pedro380085** [comment]
Finally solved the issue!

Solution: The ` submission_information true` call must be on the same DeliverFile where you call `submission_information ({})`. If **both** are not on the same file, submission fails silently!

Reason: I use multiple versions of DeliverFiles, so I was updating them on different moments. Very dumb mistake never thinking about trying both at the same time, but now its solved :)
