### ISSUE TITLE
Replace only new screenshots, problem with screenshot order

### ISSUE THREAD

**Issue by srudoi** [fastlane/deliver#500]
Often I have to change only one screenshot out of five. After I download everything from iTunes Connect into the project folder, and then replace only one of the screenshots, during upload to iTunes Connect it still uploads every screenshot - not only the ones changed. Is there any workaround for this?

Another thing is that I have a problem with the screenshots order. For example, I download from iTunes Connect all the screenshots, and their names are "1_...", "2_...", etc. I replace one of them (lets say, second one), then I run deliver, and besides uploading all of them, sometimes it places the new screenshot at the end instead of putting them in the correct order. However, it doesn't happen with all languages and formats (in 60% of cases). I really have no idea why that happen...

Thanks!

**Comment by KrauseFx** [comment]
Screenshots should be sorted alphabetically by default. What happens if you run `deliver download_screenshots` and then `deliver`?
