### ISSUE TITLE
deliver shows all snapshot generated screenshots - not just those framed by frameit

### ISSUE THREAD

**Issue by siburb** [fastlane/deliver#504]
I'm using snapshot and frameit, then previewing the upload using deliver. Currently, it is always showing all of the screenshots from the screenshots folder, not just those with "framed" in the filename.

I can't find a way to either clean-up "unframed" screenshots following framit running, or ignore the "unframed" screenshots using deliver.

**Comment by KrauseFx** [comment]
Can you try the latest `deliver` release? This issue should be fixed :+1:
