### ISSUE TITLE
Only Submit app for review if Binary (ipa) was uploaded one day ago.

### ISSUE THREAD

**Issue by sarthak03** [fastlane/deliver#505]
Hey

As iTunes takes lot of time in processing, I was thinking if there is a way to only submit the app for review (i.e. select the last uploaded binary and submit it). I tried commenting everything, and make submit_for_review true in the deliverfile. This worked partially i.e. the latest build was automatically selected which was uploaded earlier and deliver even displayed `submitted app for review succesfully`, although the app was not submitted.

So, maybe 'submit for review' feature of deliver is not working.

Attaching log -

```
[14:29:45]: Making sure the latest version on iTunes Connect matches '2.3' from the ipa file...
[14:29:48]: '2.3' is the latest version on iTunes Connect
[14:29:52]: Finished the upload to iTunes Connect
[14:29:52]: Selecting the latest build...
[14:29:57]: Selecting build 2.3 (2)...
[14:30:00]: Successfully selected build
[14:30:00]: Submitting the app for review...
[14:30:14]: Successfully submitted the app for review!

```

**Comment by ffittschen** [comment]
I really like the idea! Because usually I upload an `ipa` to Testflight, test everything and then all I need is something like `deliver --skip-ipa` which uploads all metadata and selects the latest uploaded ipa

**Comment by bastibense** [comment]
+1

**Comment by cybertk** [comment]
This can be achieved by don't provide `--ipa` option.

**Comment by jaleksynas** [comment]
+1, it is a little tricky/confusing to remove the --ipa option when using deliver in fastlane.  
It would be more clear to have an explicit option for this promotion/submit operation.  Further, an accompanying 'build_number' optional option to select a specific binary (the highest being sensible default).
