### ISSUE TITLE
The App Name you entered has already been used

### ISSUE THREAD

**Issue by sareninden** [fastlane/deliver#515]
Hey, just started using fastlane at our company after a presentation about fastlane at an ios conference.

I have an app with two versions (free with ads and a paid version).
I tried setting up deliver (without ipa) for only the screenshots and marketing texts.
It downloaded everything perfectly from the app store, updated it and tried to upload it (also using fastlane).

Both the app identifiers are already registers and live so that 'the app name has already been used' error seems a bit weird to me.

Also it works fine for the paid version (uploading) but for the free version it failed. A report should have been submitted under the id 'd9634e9047b9dbc52913670181da6ce8'

The lane is called 'uploadScreenShotsFree' but since no bundle identifier has been provided it does not really matter.

Perhaps i'm doing something wrong or something is wrong or apple is being vague, I really have no idea how to fix this.

Anyway thanks for reading, thanks for this great tool and also thanks in advance for helping.

Terminal input
Sarens-iMac:ios_app_calculatorpro sareninden$ fastlane uploadScreenShotsFree
Your Apple ID Username: ************************
[16:45:30]: Login to iTunes Connect (************************)
[16:45:33]: Login successful
The Bundle Identifier of your App: com.guyescalculator.calculatorprofree

Appfile.txt and Deliver.txt are completely commented out

Fastfile.txt:

fastlane_version "1.32.1"
default_platform :ios
platform :ios do
  desc "Upload Screen Shots Free Version"
  lane :uploadScreenShotsFree do
    deliver(force: false)
  end
end

**Comment by KrauseFx** [comment]
As the title already says `The App Name you entered has already been used`, the app name of the app is already taken by someone else. Some other company (or yourself) already use this name.

**Comment by sareninden** [comment]
Thanks for the quick reply.

Yes that much is right, we already have an app live under this identifier.
We have two apps, one free one paid both under the same account.

If I execute 'fastlane uploadScreenShotsFree' with 'com.guyescalculator.calculatorprofree' i get this error. But if i do it with the same account and 'com.guyescalculator.calculatorpro' as identifier (the paid version) it all works fine.

I thought perhaps since i have multiple team under my account something went wrong so i tried defining them in Appfile and later on Deliverfile without any succes.

(side note if i define them in the app file it is not recognized, so i ended up defining them in the Deliverfile).

But do you have any idea what could cause this since the commands are exactly the same (except for the app identifier) and both app identifiers are owned by the same account and one always succeed and one always fails.

**Comment by none2011** [comment]
+1, same problem.

**Comment by samrobbins** [comment]
@sareninden do `com.guyescalculator.calculatorprofree` and `com.guyescalculator.calculatorpro` share the same name or they have different names in `iTunesConnect`?

**Comment by sareninden** [comment]
They have different names, 'Calculator HD' and 'Calculator HD Free'
