### ISSUE TITLE
Skipping certain languages

### ISSUE THREAD

**Issue by lilidotshi** [fastlane/deliver#516]
I tried searching through issues, but couldn't find a solution. I keep getting errors every so often when uploading screenshots. I noticed deliver went from saving at the very end to saving after every individual language upload. Is there a way to specify which languages to upload? I've successfully uploaded danish, so I don't need to any more, but it keeps failing intermittently and I want to skip danish and try greek until it goes through.

**Comment by anclefeudor** [comment]
Look, i leave only one folder for ex. "en-US" in "screenshots", and start deliver with ```skip_metadata: true```. And it seems to works.

**Comment by KrauseFx** [comment]
Sorry, it's only possible to upload all screenshots.

**Comment by tabrindle** [comment]
+1 This is a major issue. We all know how finicky Apple's sites and APIs can be - and it doesn't seem like a good solution to just move files around. 

Surely there is a way to add a feature to specify which localization - en-us or zh-hant etc - to upload? Or maybe intelligently retry if the connection drops etc?

**Comment by carles** [comment]
+1 I've been trying to upload a new version of our app like 5 times already. Every time it will get a connection error at some random point and I have to start all over again.

**Comment by tabrindle** [comment]
@anclefeudor suggested moving language folders out of the screenshots directory, and I have confirmed that works. But that's a really hacky solution and almost defeats the purpose of automating this.

**Comment by lilidotshi** [comment]
Could the script set up a "done" folder to place all the finished
screenshots?

**Comment by Tibbs** [comment]
I use this script to keep repeating:
`until deliver --skip_metadata -f; do echo "Try again"; sleep 2 ; done`

It is usually done overnight.

Moving finished languages out seem to work as well.
