### ISSUE TITLE
Apple TV binary/screenshots/metadata not supporterd

### ISSUE THREAD

**Issue by Alx06** [fastlane/deliver#528]
I'm trying to use fastlane deliver on a project that contains an iOS binary and a TV OS binary too.
When using "fastlane init" I'm getting "only" the iOS metadata/screenshots, and not the Apple TV ones.

Is there a way to get them?

**Comment by KrauseFx** [comment]
This is now available in the next release :+1:

**Comment by Alx06** [comment]
Thanks for taking that in account but I've installed version 1.7.0 and there is nothing new.
Maybe I'm not using 'deliver' how I should, I just ran 'deliver init' and see only the ipad/iphone/ipone5 screenshots being downloaded (not the apple tv one's). But all screenshots are named with the suffix '_tv'.

I don't know what to do, sorry.

**Comment by samrobbins** [comment]
@Alx06 is the app an iOS tvOS hybrid that shares a single bundle id? If so we don't support that only a single bundle id to tvOS app currently. We need to change a lot in `spaceship` to support that. Let me know, happy coding.

**Comment by Alx06** [comment]
Yes, this is an "universal" app, with a binary for iOS and one for TV OS.
I should have said that before, sorry.
Good luck for that!
