### ISSUE TITLE
Download dSYMs for bitcode-enabled Apps

### ISSUE THREAD

**Issue by klavergne** [fastlane/deliver#537]
We are uploading our app with Deliver, and our next version will have bitcode enabled. Does Deliver, or some other Fastlane tool, provide a way to download the dSYM files for bitcode-enabled apps?

**Comment by KrauseFx** [comment]
Sorry, no

**Comment by klavergne** [comment]
Do you have any plans to add that feature? Do you know if Apple supports downloading dSYMs in any way except through Xcode?

**Comment by mRs-** [comment]
HockeyApp got the same problem and the current solution in the docs is: (http://support.hockeyapp.net/kb/client-integration-ios-mac-os-x/how-to-solve-symbolication-problems)

> To download the dSYMs for Bitcode enabled apps please open the Xcode's Organizer. Select the specific Archive of your app that you uploaded to iTunes Connect and click on the "Download dSYMs" button which will insert the Bitcode compiled dSYMs into the original archive. Then manually upload the symbols to the corresponding app and version on HockeyApp.

**Comment by klavergne** [comment]
It sounds like we will only be able to get dSYMs for apps that are archived and uploaded via Xcode, but not tools like Deliver. Is this true?

**Comment by mRs-** [comment]
No it should be available to all builds
