### ISSUE TITLE
Support for Universal tvOS/iOS apps

### ISSUE THREAD

**Issue by hufkens** [fastlane/deliver#539]
I tried the latest version of fastlane and deliver on my tvOS project. The project is not a standalone tvOS app, but I added one to my iOS app.

When I run deliver it will only download the iOS part. Technically both Xcode projects are different projects and can have a different fastlane setup. At the moment I can't find a way to set this up.

Is there a way to use fastlane on tvOS project that has the same bundle id as it's iOS app?

**Comment by samrobbins** [comment]
@hufkens There are some assumptions in `spaceship` that make this a non trivial task, at least in my eyes. I would like to tackle this at some point but it's not on the horizon yet. Happy coding.

**Comment by hufkens** [comment]
All right. Good to know. I just wanted to check since the tvOS support was announced. So building with gym should work, only the iTunes Connect stuff is not yet supported. Right?

Keep up up the good work 👍
