### ISSUE TITLE
`deliver init` should also download the app icon by default

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/deliver#542]
`deliver init` should download and store the app icon in `fastlane/metadata` by default. Additionally the app icon should automatically be detected in the `metadata` folder

**Comment by KrauseFx** [comment]
@ohwutup could you take a look at this, as it has a lot to do with the fastlane setup process? This can wait until after the the new `fastlane init` was uploaded

**Comment by owurman** [comment]
Can this also be added to "deliver download_metadata"?

**Comment by KrauseFx** [comment]
This is actually not implemented yet, I'll re-open the issue for now :+1:
