### ISSUE TITLE
Spaceship/deliver issue, UnexpectedResponse, aka loss of connection

### ISSUE THREAD

**Issue by Bureauwlamp** [fastlane/deliver#554]
https://github.com/fastlane/spaceship/issues/115 
I was told to place this issue here, since it involves deliver instead of spaceship.

> I'm still getting this error from time to time. It gets pretty annoying when I'm trying to upload 25 screenshots for 25 localizations, especially because the process has to be restarted. I remove/move the folders from the localizations that were already uploaded so that deliver doesn't re-upload those again.

> Isn't there a way to let Deliver retry the connection after this error? So that it continues where it left of? That's the beauty of this tool, that it does all the hard work while you continue with something else :) Now I have to get back every time to restart the process...

> > Saving changes
[16:24:18]: Uploading 25 screenshots for language es-MX
[16:24:18]: Uploading './screenshots/es-MX/1_ipad_1.b6429e9e2af4f3b58b3eaca42548e49d.png'...
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.1/lib/spaceship/client.rb:268:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)

It's nothing big, because I can just restart the process, but it's a minor fault that could maybe be overcome by 'just' restarting and continuing the upload process?

**Comment by ZackaryVink** [comment]
I am also having this issue.

**Comment by KrauseFx** [comment]
Please update spaceship using `sudo gem update spaceship`

**Comment by Bureauwlamp** [comment]
I've updated

> Updating installed gems
Updating spaceship
Fetching: spaceship-0.19.3.gem (100%)
Successfully installed spaceship-0.19.3
Parsing documentation for spaceship-0.19.3
Installing ri documentation for spaceship-0.19.3
Installing darkfish documentation for spaceship-0.19.3
Done installing documentation for spaceship after 5 seconds
Parsing documentation for spaceship-0.19.3
Done installing documentation for spaceship after 1 seconds
Gems updated: spaceship

Also tried updating deliver and fastlane. Started uploading and after a while:

> [10:45:12]: Uploading './screenshots/ja/4_iPad_ja.png'...
[10:45:43]: Uploading './screenshots/ja/5_ipad_5.iOS-iPad_5_ja-JP.png'...
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.3/lib/spaceship/client.rb:268:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.3/lib/spaceship/tunes/tunes_client.rb:483:in `ref_data'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.3/lib/spaceship/tunes/tunes_client.rb:785:in `sso_token_for_image'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.3/lib/spaceship/tunes/tunes_client.rb:443:in `upload_screenshot'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.3/lib/spaceship/tunes/app_version.rb:348:in `upload_screenshot!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.8.1/lib/deliver/upload_screenshots.rb:42:in `block (2 levels) in upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.8.1/lib/deliver/upload_screenshots.rb:29:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.8.1/lib/deliver/upload_screenshots.rb:29:in `block in upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.8.1/lib/deliver/upload_screenshots.rb:27:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.8.1/lib/deliver/upload_screenshots.rb:27:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.8.1/lib/deliver/runner.rb:54:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.8.1/lib/deliver/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.8.1/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.8.1/lib/deliver/commands_generator.rb:107:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.8.1/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.8.1/bin/deliver:5:in `<top (required)>'
	from /usr/bin/deliver:23:in `load'
	from /usr/bin/deliver:23:in `<main>'

**Comment by alistra** [comment]
Also having this on newest version.

I'm uploading 30 screens x 12 languages x 20 apps, and basically it never got to go through a whole app (30 screens x 12 languages).

It crashes randomly at some point during uploading batches.

**Comment by alistra** [comment]
```
[14:58:56]: Uploading '/Users/alistra/dev/ios-codebase/ios-bravefrontier/deliver-screenshotspxLiCq/ja/1.png.pngcrush.pngf45bbc87-f198-449b-822a-0dea09673093.png'...
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.19.3/lib/spaceship/client.rb:268:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.19.3/lib/spaceship/tunes/tunes_client.rb:483:in `ref_data'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.19.3/lib/spaceship/tunes/tunes_client.rb:785:in `sso_token_for_image'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.19.3/lib/spaceship/tunes/tunes_client.rb:443:in `upload_screenshot'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.19.3/lib/spaceship/tunes/app_version.rb:348:in `upload_screenshot!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.8.1/lib/deliver/upload_screenshots.rb:42:in `block (2 levels) in upload'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.8.1/lib/deliver/upload_screenshots.rb:29:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.8.1/lib/deliver/upload_screenshots.rb:29:in `block in upload'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.8.1/lib/deliver/upload_screenshots.rb:27:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.8.1/lib/deliver/upload_screenshots.rb:27:in `upload'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.8.1/lib/deliver/runner.rb:54:in `upload_metadata'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.8.1/lib/deliver/runner.rb:21:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.8.1/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.8.1/lib/deliver/commands_generator.rb:107:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.8.1/lib/deliver/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.8.1/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'
```

**Comment by ZackaryVink** [comment]
I am getting the same error on the updated version as well, however it did work once after re-running it a handful of times

**Comment by gsempe** [comment]
Same kind of problem here.
Impossible to upload all my screenshots (already tried more than 20 times) because it fails randomly on saving changes between two languages.
Deliver can not be used like this because it always fails as I have more than 10 languages

**Comment by Dimillian** [comment]
Yes, it actually have the same behaviour as iTunes connect when shaving changes. It times out and log you out on the website. It's exactly what deliver report in the error

```
16:38:59]: Saving changes

/Users/Dimillian/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.19.3/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] Unauthorised access (Spaceship::TunesClient::ITunesConnectError)

```
