### ISSUE TITLE
ITC App Ratings: Made for Kids checkbox?

### ISSUE THREAD

**Issue by dpettit** [fastlane/deliver#574]
ITC ratings section includes a checkbox that is labeled "Made for Kids".

I haven't been able to find it in any of the Fastlane documentation.  I found the ratings documentation for deliver, but it doesn't appear to include "Made for Kids" data.

Does Fastlane support a way to populate this data element?  If so, where can I find documentation on how to set it?  If not, do you have any plans to support this data element in the near future?

**Comment by mfurtak** [comment]
Hi @dpettit - thanks for the report! :+1: 

I think you're right that we don't support that right now. @snatchev, are we correct about that?

**Comment by dpettit** [comment]
Thank you for listening!

Just FYI, The "Made for Kids" checkbox and "Target Age Range" data elements
are required for apps that are specifically targeted for children, in order
to comply with the standards set forth in the Children's Online Privacy and
Protection Act (COPPA), a U.S. law enacted several years ago.  Apple
requires that these fields be populated if the app is to be eligible for
release under the "Made for Kids" section of the App Store.

I publish Childrens Book Apps, so that is why it is of critical
importance to me.  However, anyone who creates any content targeted
for children will probably be very interested in them as well.

Thank you so much for all you are doing to make these tools available to us!
