### ISSUE TITLE
'default' release_notes in Deliverfile gives error on tunes_client.rb:207:in `handle_itc_response': [!] There are one or more errors on the page.

### ISSUE THREAD

**Issue by owurman** [fastlane/deliver#583]
If I have the following in my Deliverfile:

release_notes({
  'default '=> "Testing"
})

Then I get the following error when running `deliver --skip_screenshots --skip_binary_upload
`:

> /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] There are one or more errors on the page. (Spaceship::TunesClient::ITunesConnectError)
> 	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:347:in `update_app_version!'
> 	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/app_version.rb:269:in `save!'
> 	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.2/lib/deliver/upload_metadata.rb:130:in `verify_available_languages!'
> 	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.2/lib/deliver/upload_metadata.rb:22:in `upload'
> 	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.2/lib/deliver/runner.rb:58:in `upload_metadata'
> 	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.2/lib/deliver/runner.rb:21:in `run'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/actions/deliver.rb:18:in `run'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:129:in `block in execute_action'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:128:in `chdir'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:128:in `execute_action'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/fast_file.rb:149:in `method_missing'
> 	from (eval):83:in `block (2 levels) in parsing_binding'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/lane.rb:36:in `call'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/lane.rb:36:in `call'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:52:in `block in execute'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:46:in `chdir'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:46:in `execute'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/command_line_handler.rb:30:in `handle'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/bin/fastlane:38:in `block (2 levels) in run'
> 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
> 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
> 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
> 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
> 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/bin/fastlane:150:in `run'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/bin/fastlane:156:in `<top (required)>'
> 	from /usr/bin/fastlane:23:in `load'
> 	from /usr/bin/fastlane:23:in `<main>'

Removing the release_notes fixes the issue. I have fully updated fastlane, deliver and spaceship.

In the verification html, it shows:

> en-US
> Changelog
> Screenshots
> Skipped Screenshots
> 
> Options to skip_screenshots activated. deliver will not modify your app screenshots.

**Comment by owurman** [comment]
The same error reproduces when passing the release_notes directly as a hash in my Fastfile using they key 'en-us', but 'en-US' worked. So it might be an error with a bad key, but isn't 'default' a valid key for the hash per the documentation?

https://github.com/fastlane/deliver

**Comment by owurman** [comment]
Side-issue: metadata/en-US/release_notes.txt seems to be ignored.

**Comment by vpolouchkine** [comment]
Looks like you have an extra space in `'default '=> "Testing"`.

**Comment by owurman** [comment]
So it does. I'll try again later today when I'm submitting another update, using 'default' properly. However, it would be great if keys could be checked for validity and a meaningful error returned. I'm happy to look at doing this.

**Comment by vpolouchkine** [comment]
Go for it. :+1:

**Comment by owurman** [comment]
So I tried using "default" again. No crash (yay) but it didn't change anything for en-US and eventually error'd with 

> /Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.0/lib/spaceship/tunes/tunes_client.rb:219:in `handle_itc_response': [!] You must detail what's new in this version in English. (Spaceship::TunesClient::ITunesConnectError)

I guess I don't understand what default is supposed to do, if not fill in for any language that isn't explicitly defined?

**Comment by vpolouchkine** [comment]
Perhaps @ConfusedVorlon can chime in?

**Comment by ConfusedVorlon** [comment]
@owurman - which build are you using? The default functionality was broken in the last release, though it has been fixed in head. I'm getting on a plane shortly, so I'll be unavailable for about 48 hrs, but I can check properly when I get to the other end.

What you're doing looks correct - the idea is that 'default' is just treated like a language key in the hash.If you're willing to debug, then have a look at ```upload_metadata.rb/assign_defaults````

also worth checking with a file-system approach. Create a /default folder in your metadata folder (right next to your other languages), and put release_notes.txt (check that the name is correct) with 'test' as the content

**Comment by owurman** [comment]
I was using 1.63.1 which probably has that broken functionality. I'll wait for the next release and try again.
