### ISSUE TITLE
deliver download_metadata appending metadata to path

### ISSUE THREAD

**Issue by owurman** [fastlane/deliver#584]
Default metadata_path is ./fastlane/metadata, but
`deliver download_metadata`
seems to append another /metadata:

> +------------------------+---------------------------------------+
> |                     deliver 1.10.2 Summary                     |
> +------------------------+---------------------------------------+
> ...
> | metadata_path          | ./fastlane/metadata                   |
> ...
> +------------------------+---------------------------------------+
> 
> Do you want to overwrite existing metadata on path '/Users/oded/Documents/xCode Projects/ParamedicProtocolProvider/Custom/Kalitta/fastlane/metadata/metadata'? (y/n)

**Comment by seapy** [comment]
Same to me

**Comment by KrauseFx** [comment]
This was introduced with https://github.com/fastlane/deliver/pull/567. @martinjuhasz does https://github.com/fastlane/deliver/pull/568 fix this issue?

**Comment by martinjuhasz** [comment]
yes it does. But found a typo and fixed that. just trying to sqash my 3 commits now
