### ISSUE TITLE
Deliverfile - description with newline

### ISSUE THREAD

**Issue by gran33** [fastlane/deliver#585]
Hi,
I have a `Deliverfile` with description in it, the description include `newline` characters. `Fastlane`/`iTunes` refuse to handle this `newline` characters.

How can I escaping `newline` characters in the description section in the `Deliverfile`?

Example:
description({
  "en-US" => "I'm an awesome app!
U should download me NOW"
})

**Comment by KrauseFx** [comment]
Since the `Deliverfile` is just a Ruby file, you can use https://stackoverflow.com/questions/2060253/how-to-do-a-newline-in-output :+1:

**Comment by gran33** [comment]
If will help to someone, I'm using `shell script` a.k.a `bash` language to my build and deploy stuff.
So I m using `sed` for replace patterns but I m escaping some special characters, I'm doing it like this:
`local valueWithEscaping=$(echo "${originalValue}" | sed -e 's/[]\/$*.^|[]/\\&/g')`
`sed -i "s|__VALUE_TO_REPLACE__|${valueWithEscaping}|g;" <input_file> ` 
The `-i` is for in place replace.
