### ISSUE TITLE
Deliverfile and metadata_path

### ISSUE THREAD

**Issue by gran33** [fastlane/deliver#586]
Hi,

I use `Deliverfile` because there is no other way to supply `app_review_information`.
But I want to have description with newlines in it, so I need to supply `metadata_path` with `description.txt`  :-/

Can I use `metadata_path` and `Deliverfile` together?

**Comment by KrauseFx** [comment]
Yeah, you can use them together.

**Comment by gran33** [comment]
@KrauseFx  Thanks for the quick answer.

How can I work with both of them?

If I have `description.txt` in the metadata folder and description in the `Deliverfile`, which one will take into account?

**Comment by KrauseFx** [comment]
Deliverfile will be preferred :+1:

**Comment by KrauseFx** [comment]
You can read more about this here: https://github.com/fastlane/fastlane/blob/master/docs/Advanced.md#priorities-of-parameters-and-options
