### ISSUE TITLE
Try to submit to review without busy waiting

### ISSUE THREAD

**Issue by gran33** [fastlane/deliver#600]
Hi,

I would like to sample `iTunes Connect` with `Deliver` in my `CI` but without stuck the process.
I mean to have the ability to sample `Deliver`/`iTunes Connect` just once and success/fail if the submit really happened but without waiting to the `Deliver` busy waiting.

Does `Deliver` have this option?

10x in advance!

**Comment by gran33** [comment]
By the way,
I LOVE U!
Because of this:
https://github.com/fastlane/watchbuild

**Comment by KrauseFx** [comment]
Hey @gran33, so does `watchbuild` fix your issue? :+1:

**Comment by gran33** [comment]
@KrauseFx  It might be.
I didn't find in the docs how `watchbuild` will exactly notify me when the file is done processing.
I saw this:

> Once the build is ready to be pushed to TestFlight or for review, you get a OS X notification


But if the process run on the `CI` so it won't help me :/
