### ISSUE TITLE
Automating Release Notes with Deliver

### ISSUE THREAD

**Issue by sdprogov** [fastlane/deliver#605]
Not exactly an issue but an enquiry, Deliver you can automate screenshots, IPA files, and meta data. Is there a way to send release notes to iTunes connect? With all the bug tracking software (like Jira) that generates release notes automatically, I would think this would be a handy addition if possible. 

Couldn't find anything about this either in the help or other documentation, thanks!

**Comment by vpolouchkine** [comment]
Take a look at the `--release_notes` argument. You can run `deliver help` to get the full list.

**Comment by sdprogov** [comment]
Hi,

--release_notes seems to just give all the release notes regarding deliver. Not uploading *your* release notes to the app store. Or am I missing something?

I ran deliver --release_notes inside my project file and just received the release notes for deliver

**Comment by vpolouchkine** [comment]
Take a look at https://github.com/fastlane/deliver#default-values on how to include release_notes in your Deliverfile :+1:
