### ISSUE TITLE
Deliver should sync screenshots

### ISSUE THREAD

**Issue by lacostej** [fastlane/deliver#611]
I think that deliver should sync screenshots smartly.

Scenarios: if you asked to upload screenshots:
* if you have no screenshots locally and asked to upload screenshots, it should delete those on ITC
* if you have removed one screenshot, it should remove it on ITC
* if you have already uploaded a screenshot, it should avoid uploading it again
* nice to have: if you reorder the screenshots, it should try to reorder them on ITC

Related #597, #550, #500

Scenarios: if you asked to download screenshots
* if should rename the screenshots the proper way

Somewhat related #170, #364

Scenarios: 
* upload after download should basically do nothing :)

We are working on a solution, involving using MD5 for identifying already uploaded screenshots.

**Comment by KrauseFx** [comment]
Great plan, keep me up to date :+1:
