### ISSUE TITLE
Primary Language

### ISSUE THREAD

**Issue by MickeyHub** [fastlane/deliver#613]
Could `deliver` set `primary language` or add `localized languages` ?
sorry, I can't get it from [README](https://github.com/fastlane/deliver/blob/master/README.md) and [Deliverfile.md](https://github.com/fastlane/deliver/blob/master/Deliverfile.md)

**Comment by vpolouchkine** [comment]
Sure, take a look at https://github.com/fastlane/deliver/blob/master/README.md#default-values

**Comment by MickeyHub** [comment]
**Default language** in `deliver` is **primary language** in `iTunes Connect` ? sorry, I do not think so.
In my view,  default language is default value for other language (including primary language in iTC)
for example:
```text
default
      keywords.txt     
      marketing_url.txt
      name.txt
      privacy_url.txt
      support_url.txt
      release_notes.txt
   en-US
      description.txt
   de-DE
      description.txt
   el
      description.txt
   it
      description.txt
```

maybe en-US is `primary language` in `iTC`, default is only a convient approach to set value for each, it's not a language.

**Comment by vpolouchkine** [comment]
I don't believe you can set the primary language, but you can use the following language codes https://github.com/fastlane/deliver/blob/master/README.md#available-language-codes to localize other metadata (for the full list, run `deliver help`).

**Comment by MickeyHub** [comment]
Thanks @vpolouchkine , so the conclusion is that I can not set one language to primary language in ITC using deliver ?
I should login the iTC , set primary language, and add some localized languages, then set values for them locally using deliver?

**Comment by vpolouchkine** [comment]
That should work.
